### ISSUE TITLE
Add module about image filter pros & cons

### ISSUE THREAD

**Issue by tobyhodges** [NEUBIAS/training-resources#15]
quoting @tischi from the old repository:

> It would be great to have a module that compares the pros and cons of popular filters, e.g., such as:
> 
> - Gaussian Blur
> - Median Filter
> 
> Maybe we should restrict ourselves to maximally comparing three (better only two) filters per module. To compare other filters we could make a new module. This would keep it nicely modular and at the same time not overload the students with information.

**Comment by manerotoni** [comment]
This topic is handled in the different filters modules.
