### ISSUE TITLE
Make landing page simpler and more attractive.

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#159]
@manerotoni @tobyhodges 

I feel that the landing page right now is full with quite a lot of text and menu items. I think it would be great if we could redesign it to make it more attractive and simpler, maybe just containing the modules and a link to all the other information.

**Comment by tischi** [comment]
@manerotoni Do you know someone with www programming experience to do this? 
If not, do you mind if I ask around at EMBL? We could also reach out to NEuBIAS community!

**Comment by tischi** [comment]
@tobyhodges Could you point me to the place in all the jekyll files where the layout of the [landing page](https://neubias.github.io/training-resources/) is defined?

**Comment by tischi** [comment]
Found it, never mind. Sorry for the ping!

**Comment by tischi** [comment]
I found out: 

- The modules are a so-called `collection`. So if we could find out how to display a `collection` in Jekyll in an attractive way that would be a first step.
- Here seems to be already something to show all modules: https://neubias.github.io/training-resources/aio/index.html (seems to have to do with `/_includes/aio-script.md` and `/aio.md`, aio=all in one)

**Comment by tischi** [comment]
What would be cool is having an interactive graph that shows the connection between the teaching modules. The node=module that one clicks at could move into the center.

**Comment by tischi** [comment]
Made a branch to work on this: https://github.com/NEUBIAS/training-resources/tree/beautiful_landing_page

**Comment by tischi** [comment]
> You may also be inspired by the current landing page of the Bio-IT website which breaks content into four boxes or any of the multiple column Bootstrap [1] or Bulma [2] grid/tile layouts.

[1] https://getbootstrap.com/docs/4.0/components/card/#using-grid-markup
[2] https://bulma.io/documentation/layout/tiles/

**Comment by tischi** [comment]
@unode I started playing a bit and I managed already quite some stuff. However now I am a bit stuck. I have a feeling that I somehow need to install bootstrap on my mac and also add some stuff to the repo?

More specifically, things like that work in principle
```
<div class="col-sm-6">
  <div class="card border-primary bg-dark" style="max-width: 24rem;">
    <div class="card-header">{{ e.title }}</div>
    <div class="card-body">
      <h5 class="card-title">Info card title</h5>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    </div>
  </div>
</div>  
```

But it totally ignores `border-primary bg-dark`, which is why I feel that maybe those guys need to be defined in one of the sass files?

Any ideas?

**Comment by tischi** [comment]
More specifically I think I probably need to add those lines somewhere but I am not sure where and I am not sure whether I should also install something locally on my Mac?

```
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
```

**Comment by unode** [comment]
You shouldn't need to install anything on your computer.
Just add those 4 lines to the `<head>` section of the HTML page and after a refresh any element with bootstrap CSS should have a bootstrap style.

**Comment by tischi** [comment]
@unode 

Thanks!

Do you happen to  know where to add this? I have a feeling that the `<head>` part is added by Jekyll to all pages.

I found some places:

- https://github.com/NEUBIAS/training-resources/blob/master/_includes/head.html
- Here is something with bootstrap already: https://github.com/NEUBIAS/training-resources/blob/0be794070c98a0e8879f36e39f432cbd7f7f3f05/_layouts/base.html#L15
- https://github.com/NEUBIAS/training-resources/blob/0be794070c98a0e8879f36e39f432cbd7f7f3f05/_layouts/workshop.html#L8

**Comment by tischi** [comment]
Hmmm, the site where I am trying to get the bootstrap cards to work seems to have some bootstrap already (see below). Maybe that's not sufficient?

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/2157566/144828291-49e4cc55-0e02-4bd9-9cfa-530cb7456e01.png">

**Comment by tischi** [comment]
Also some bootstrap js seems to be there:

<img width="597" alt="image" src="https://user-images.githubusercontent.com/2157566/144829001-a6ece3f2-99be-4d51-88fb-d4c920a4f0b4.png">

**Comment by unode** [comment]
Then you don't even need to add anything else. The page is already bootstrap capable.
Check perhaps the header of the bootstrap.css file to know which bootstrap version it is using. Might still be bootstrap 4 and the latest bootstrap version is 5.1.

**Comment by tischi** [comment]
Here it is https://github.com/NEUBIAS/training-resources/blob/0be794070c98a0e8879f36e39f432cbd7f7f3f05/assets/css/bootstrap.css#L2

They seemed to have copied the whole stylesheet into the repo....

Maybe it would be easier to use this: https://bulma.io/documentation/layout/tiles/
As this would not clash with the Carpentries' bootstrap css.

What do you think?

**Comment by tischi** [comment]
Note to self: `border-primary` `bg-dark` are indeed [not supported here](https://github.com/NEUBIAS/training-resources/blob/0be794070c98a0e8879f36e39f432cbd7f7f3f05/assets/css/bootstrap.css#L2). Maybe I could just define those via an inline `style`.

**Comment by unode** [comment]
Check if Bootstrap 3 already includes the features you need. There are online docs for each bootstrap version, [including 3.x](https://getbootstrap.com/docs/3.4/css/#grid).
Going with bulma might work but I don't know if there are any interactions or incompatibilities between the frameworks.

**Comment by tischi** [comment]
@unode in fact, it would be very nice to have the `card` class available, which seems to be bootstrap 4: https://www.w3schools.com/bootstrap4/bootstrap_cards.asp
Any advice how to get this in?

**Comment by unode** [comment]
[This](https://stackoverflow.com/a/59833413) may be an alternative.
Upgrading to Bootstrap 4 or newer will need changes to the rest of the project.

I guess you can always try bulma as well and see if nothing breaks.
I don't really have practical advice to give as I don't have experience with combining these technologies.

**Comment by tischi** [comment]
@unode
I made some progress :-)
Could be more beautiful but it's not bad either:
https://neubias.github.io/training-resources/all-modules/index.html
Thanks for the help!

**Comment by manerotoni** [comment]
Cool.

**Comment by tischi** [comment]
I should try this:

```
<div class="panel panel-default">
  <div class="panel-heading">Panel Heading</div>
  <div class="panel-body">Panel Content</div>
  <div class="panel-footer">Panel Footer</div>
</div>
```

**Comment by tischi** [comment]
- [ ] Fix blank spaces [in the rendered page](https://neubias.github.io/training-resources/all-modules)
