### ISSUE TITLE
Please make me admin again

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#161]
@tobyhodges @ssgpers  I accidentally removed myself the admin rights from this repo. Could you please grant me again?

**Comment by ssgpers** [comment]
I can not find the place where I can do it. Most likely I am not admin of the github repo

**Comment by miura** [comment]
done!

**Comment by miura** [comment]
I also added Alex as an Admin.

**Comment by tischi** [comment]
Thanks @miura !
