### ISSUE TITLE
New folder for scripts

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#170]
@manerotoni 

Should we make a new folder called `scripts` (similar to `image_data`).
I think we need this to store the example scripts for the new material.

**Comment by manerotoni** [comment]
Yes. This is kind of example data. Then you link the file to the solutions. A link is easier to maintain. 
Alternatively one could embed it in the solutions as we usually do, but it is more hassle.

**Comment by tischi** [comment]
OK, I will do it.
