### ISSUE TITLE
string_concat module file path handling

### ISSUE THREAD

**Issue by manerotoni** [NEUBIAS/training-resources#199]
Hi @elnazfazeli, @tischi, and @AnniekStok 

I wonder if in the string_concat module one should also handle the file path issue. This is one of the first headaches with special characters. "\" does not work you need to use r"\" or "\\" or "/". 

This knowledge is also useful for the saving output module. 

Antonio

**Comment by tischi** [comment]
Yes, we could use creating a full path from a directory and a file name as an example for string concatenation.

In IJ-Macro there is [File.separator](https://imagej.nih.gov/ij/developer/macro/functions.html#F), which is I think something we may teach as this is best practice.

**Comment by elnazfazeli** [comment]
I'm adding this to motivation and as an external reading list
