### ISSUE TITLE
Apply template to modules

### ISSUE THREAD

**Issue by tobyhodges** [NEUBIAS/training-resources#2]
The following modules need to be converted to the new(-ish) template. See [the contributing guide](https://github.com/NEUBIAS/training-resources/blob/master/CONTRIBUTING.md) for instructions.

- [ ] Automated object filtering
- [ ] Basic image analysis workflow
- [x] Connected components 
- [ ] Recap
- [ ] Distance transform
- [ ] Image feature enhancement
- [ ] Image math
- [ ] Difference of Gaussian
- [ ] Morphological filters
- [ ] Rank filters
- [ ] Image display
- [ ] Image data integrity
- [ ] Local background subtraction
- [ ] Semantic image segmentation using machine learning
- [ ] Intensity measurements
- [ ] Object shape measurements
- [ ] Object splitting
- [ ] Pixel data types
- [ ] Pixel processing
- [ ] Real world coordinates

**Comment by manerotoni** [comment]
Most modules are in the format of the new template. It is clear which one are not and one can update them accordingly.
