### ISSUE TITLE
Minimal example material

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#20]
@haesleinhuepf

What about these modules, using an image with few nuclei as an example:

1. Basic bioimage analysis workflow overview
2. Pixels (an image is made of pixels)
3. Image binarisation
4. Image threshold (to achieve image binarisation)
5. Connected component analysis
6. Object shape measurements

- I am not sure whether 2 and 3 should be separate. Conceptually I would say they should be separate, because there are other ways to create a binary image than a threshold (e.g., machine learning). But maybe this is overdoing it...
- I would tend to avoid the pixel data type discussion at this stage and just go with 8-bit, but one could (should?) add it the pixel data type discussion at some point.

**Comment by tischi** [comment]
- [ ] Should one hold an "Image Formation" lecture before starting with the analysis?

**Comment by manerotoni** [comment]
Hello, 
I would like  to add some more workflows that may or may not overlap with other workflows. 
 
**Image restoration simple denoising**
1. Basic on what are the problems of an image coming from a microscope
2. Pixels (an image is made of pixels)
3. Image quality may be contaminated by noise. What type of noise we can have.
4. Noise can be removed by filtering (rank filter, smoothing, etc.)
5. 2D and/or 3D denoising.

**Image restoration - deconvolution**

**Image analysis - colocalization**
1. Overview of questions related to colocalization
2. Multi-color images and pixels
3. Pixel-based and object based colocalization. When to use one or the other case.
4. Object based colocalization
    
   - image binarization
   - CCA
   - distance measures or object overlap measures

5. Pixel-based colocalization

**Comment by tischi** [comment]
Sounds great!

🚀 

Just have a look whether you can reuse/improve/polish something that we have already, e.g.:
- https://neubias.github.io/training-resources/pixels/index.html
- https://neubias.github.io/training-resources/pixel_data_types/index.html
- Colocalization: https://github.com/embl-cba/imagej-courses/blob/master/practicals/colocalisation.md
- For image filtering our current idea was to start with the concept of a neighbourhood filter: https://neubias.github.io/training-resources/filter_neighbourhood/index.html
   - And then say you can do all kind of funky math (min, max, mean, median, weighted mean == convolution) with the numbers in those neighbourhoods.

Here is also more stuff that I would be very happy to convert into the format of this repo: 
https://github.com/embl-cba/imagej-courses/tree/master/practicals

ping @tobyhodges, as you can see there may be some activity in this project after some silence. Would you have the resources to answer, in case, technical questions regarding the automated web-site creation?

**Comment by tobyhodges** [comment]
Yep, I'll keep an eye out for notifications from this repository. Just make sure to @ me so I see it...

BTW the first draft of [this tutorial on Jekyll and GitHub Pages](https://carpentries-incubator.github.io/building-websites-with-jekyll-and-github-or-gitlab/) is well on its way to being finished and may be helpful for those of you spending a lot of time on this material...
