### ISSUE TITLE
Projections

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#204]
@manerotoni I will make a module about projections (sum, max, mean), OK?

**Comment by manerotoni** [comment]
Great.
When we do the microscopy course (not a special focus on Image processing) but more on how to present the result
I discuss about type of images - image formats
Bit-depth, saturation and clipping
LUT
and dimension reduction/projection. 

So this module will be very useful.

**Comment by tischi** [comment]
@manerotoni @AnniekStok @elnazfazeli @stemarcotti 
Do you have a figure that explains, e.g., a maximum projection from 3D to 2D?

**Comment by tischi** [comment]
...and do you happen to have good example data for teaching, e.g., the difference of max and sum projections?

**Comment by tischi** [comment]
...and what's the easiest way in ImageJ to project along the x-axis?
@hzqfox

**Comment by tischi** [comment]
current draft for the figure:
![image](https://user-images.githubusercontent.com/2157566/149338178-77aa6d9d-213c-495d-96af-064bab56670a.png)

**Comment by tischi** [comment]
asked in the forum: https://forum.image.sc/t/imagej-gui-project-along-x-or-y-axis/61915

**Comment by stemarcotti** [comment]
![20220114_projections](https://user-images.githubusercontent.com/33655510/149526520-d073f1f8-0df0-49c7-88f0-508ed657cd4b.png)
@tischi I had something similar that I modified to match your draft, would it work? I can modify it further if anything is incorrect!

**Comment by stemarcotti** [comment]
Nope, it was an illustrator file originally! I will send it by email (can't do so here) in case it helps

**Comment by tischi** [comment]
Yes, if it is not too big I would add it to the /figures/resources folder of the repo.

**Comment by tischi** [comment]
And by the way: thank you for correcting my severe calculation mistakes! 🤣

**Comment by stemarcotti** [comment]
[20220114_projections.pptx](https://github.com/NEUBIAS/training-resources/files/7889067/20220114_projections.pptx)
@tischi the ppt version of the projections if it helps :)
