### ISSUE TITLE
Volume rendering

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#206]
Someone will work on a volume rendering module.

**Comment by tischi** [comment]
@maulakhan 
Maybe interesting?
`Plugins › Volume Viewer`?
I don't think I tried it.

**Comment by maulakhan** [comment]
This one is quite tricky and unstable. I don't use it more than just visualizing(rotating, zooming etc.).

**Comment by tischi** [comment]
OK, then let's not teach it!
I think `Plugins > 3D Viewer` is OK, is it?
If there's nothing much better I think that's the one I would use...

**Comment by maulakhan** [comment]
ah sorry I mixed Volume Viewer with 3d Viewer. Ok, then I will prepare a module with Volume Viewer.
