### ISSUE TITLE
Resources for figures

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#22]
@tobyhodges 

We were thinking again about where to store resources that are using to create the content of 
- https://github.com/NEUBIAS/training-resources/tree/master/figures

Do you think adding a subfolder `https://github.com/NEUBIAS/training-resources/tree/master/figures/resources` would make sense? And would storing google slides into this folder a good idea?

I think the alternative is a list of links to external resources, such as a Google slide, however this would be less stable (i.e. one could loose them) than storing it within the repo itself.

What do you think?

**Comment by tobyhodges** [comment]
I think it makes sense to store resources used to create figures inside the `figures` folder, yes. but slides used for presentations related to the lesson material etc would probably be better placed in the `files` directory. Slides in `.pptx` or `.pdf` format won't work great with version control but it's definitely better than nothing

**Comment by tischi** [comment]
I think the point would be _not_ to show those slides during teaching, but just use them to create the figures. For example, compose the figure in a google slide and save as png.
Would you still put the google slide into the `files` directory?

**Comment by tischi** [comment]
@tobyhodges please see my message above, maybe your notification settings are such that one has to @ you even to an issue thread where you were active in? If you just had too many other things to do, please ignore this message ;-)

**Comment by tobyhodges** [comment]
In that case, I think those would be best placed in the `figures/resources` folder as you originally suggested.

**Comment by tobyhodges** [comment]
make sure the file names match up, so it's clear which resources were used to make which images

**Comment by tischi** [comment]
@manerotoni @tobyhodges 

I added the figures/resources folder and also uploaded on ppt slide. 

One ppt slide seems to be only few kb, so that should be fine. 

Also nice would be scripts that auto-generate figures, e.g. imagej-macro code (maybe FigureJ)?
