### ISSUE TITLE
Bug in string concatenation figure

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#221]
<img width="493" alt="image" src="https://user-images.githubusercontent.com/2157566/149888623-7c307f65-4586-4563-8385-c03fc3e3e907.png">

@elnazfazeli It just occurred to me that this is wrong. Can you spot it? 😄

**Comment by manerotoni** [comment]
Yep no space

**Comment by elnazfazeli** [comment]
There is a space after Neubias. It's "Neubias " ;)
