### ISSUE TITLE
Website build fails

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#229]
@maulakhan 

After merging your PR the website does not build anymore.

Could it be that you did not check it with `make serve`?
It throws this error:
<img width="870" alt="image" src="https://user-images.githubusercontent.com/2157566/150204947-ff93f7d0-e6c3-4538-b2d9-4d7359ef7c25.png">

You can find this here:
https://github.com/NEUBIAS/training-resources/runs/4871438410?check_suite_focus=true

Could you please make a PR to fix this?

**Comment by maulakhan** [comment]
For me it works using :  
bundle exec jekyll serve

I get this:
![image](https://user-images.githubusercontent.com/17739639/150551461-17b2ce16-f18f-41eb-8198-f800a4a69c96.png)

**Comment by tischi** [comment]
@maulakhan 

OK, I see, this is a tricky one!

It turns out that this is the culprit (note the upper case `F`, probably on your computer it is lower case, is it?): 
`_includes/script_functions/activities/Function_display_slice.ijm`

And this is the problem: https://stackoverflow.com/questions/17683458/how-do-i-commit-case-sensitive-only-filename-changes-in-git

This is the solution:

`git mv _includes/script_functions/activities/Function_display_slice.ijm _includes/script_functions/activities/function_display_slice.ijm`

`git add .; git commit -m "Change file name"; git push`
```
[master db3ad2a] Change file name
 1 file changed, 0 insertions(+), 0 deletions(-)
 rename _includes/script_functions/activities/{Function_display_slice.ijm => function_display_slice.ijm} (100%)
```

Now, I hope, it should work...

**Comment by tischi** [comment]
...and it does 🥳 

https://github.com/NEUBIAS/training-resources/actions/runs/1729717256
