### ISSUE TITLE
File endings of scripts

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#23]
@tobyhodges 

The file endings in below folder are all .md

- https://github.com/NEUBIAS/training-resources/blob/master/_includes/binarization/activities/binarization_imagejmacro.md

For scripts, would it be OK to use the "native" file endings such as `binarization.ijm` instead?
This would allow to use those files directly in the software.

**Comment by tischi** [comment]
@tobyhodges 
Could you please comment on above issue?

**Comment by tobyhodges** [comment]
Yes, you can use whatever file extension you like. I don't think I knew this back when we were first setting up the site...
