### ISSUE TITLE
Output saving figure

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#233]
@AnniekStok 

Beautiful figure:

<img width="422" alt="image" src="https://user-images.githubusercontent.com/2157566/150642771-23ea8033-bdcf-40d3-b636-a4ac27c5d0bb.png">

Few suggestions:

- [ ] `Image analysis process`: maybe simply `Image analysis`?
- [ ] `Results table`: maybe simply `Table` (e.g., we also do not say "Result label mask")?
- [ ] Remove the windows around the images to make it look less like an ImageJ specific thing. For example, IMO, in the binarization module the figure is better in that sense. 
- [ ] Also for the table it would be nice to have something more neutral, e.g. in the object shape measurements module this is better, IMO.

**Comment by tischi** [comment]
Current object shape measurements figure for reference (contains no traces of ImageJ):

<img width="600" alt="image" src="https://user-images.githubusercontent.com/2157566/150643074-c710fb14-b8be-46fc-b3a1-6ac569ad807a.png">

**Comment by AnniekStok** [comment]
Thanks for your comment @tischi !

Got it, below is an updated figure.

![output_saving](https://user-images.githubusercontent.com/32863964/150676005-3a630243-aec2-4cc4-86e2-e7771c82e228.png)

If you like it I will push it again to the output_saving branch. Do I then just make a new merge request for this branch?

**Comment by tischi** [comment]
❤️ it! MUCH better!

Maybe could you also put all the text on the right above the images to make the figure more concise (smaller), e.g. "Label mask" on top of the image.

You can push again to the save branch, but first make sure to merge master into that branch:

`git checkout output_saving`
`git merge master`
`git add .`
`git commit -m "New figure"`
`git push`

And then you have to go to github website and make a new PR.
