### ISSUE TITLE
Install Jekyll on Windows

### ISSUE THREAD

**Issue by manerotoni** [NEUBIAS/training-resources#24]
@tobyhodges 
do you have some instructions on how to setup the website environment on windows? 
For instance installing Jekyll?

Thanks

Antonio

**Comment by tobyhodges** [comment]
Hi @manerotoni this guide from GitHub may help: https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/testing-your-github-pages-site-locally-with-jekyll

Please try following the instructions there and ping me again if you run into any trouble.

**Comment by manerotoni** [comment]
Hi @tobyhodges ,
I managed to install Jekyll in Winwdows. 
Still need 'make' etc. so it will take longer. Also some bin I don't have (markdown_ast.rb). Where do you get it?

I will switch to OSX and try in a second round on windows again.

**Comment by tobyhodges** [comment]
I'm afraid my Windows experience is very limited.

Now that #31 has been merged, you can try out the GitPod button from the README: https://github.com/NEUBIAS/training-resources/blob/master/README.md You will need to grant GitPod access to your repository, but then you can work on this project without the need for any local setup.

**Comment by manerotoni** [comment]
@tobyhodges 
Will gitpod then process the page and create a rendered page?

**Comment by tobyhodges** [comment]
you can edit and preview the pages through the GitPod interface and, once you're happy, commit and push them back to your fork on GitHub just like you would do from your local machine.

**Comment by manerotoni** [comment]
Hello @tobyhodges,
I like the fact that I can work on the browser. I tried to compile to also render the pages via gitpod. Rendering was the main reason to install jekyll so to be sure that it looks fine. The cool thing is that if you run `make serve` and it does compile, however I can't see the pages.  I get '/' not found or the port is not open.
Not sure what I do wrong. Could be that it does not really start the server. 

antonio

**Comment by manerotoni** [comment]
See also #40

**Comment by manerotoni** [comment]
@tobyhodges 
At the end I managed to run everything on window. I will update the contribution.md so that other people also get a description for windows.

**Comment by manerotoni** [comment]
There is a better description in contribution now on how to install and serve on windows. 
Still missing the make packages for windows.
