### ISSUE TITLE
Replace PNG figures by JPEG

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#271]
I think we should just convert all images in the figures folder to JPEG for faster rendering. 

Any objections?

**Comment by tischi** [comment]
Batch conversion on mac terminal:
`for i in *.png; do sips -s format jpeg $i --out ${i%.*}.jpg;done`

**Comment by tischi** [comment]
` cd figures`
`for i in *.png; do sips -s format jpeg $i --out ${i%.*}.jpg;done`
`for i in *.PNG; do sips -s format jpeg $i --out ${i%.*}.jpg;done`
`cd modules`
`find . -type f -name '*.txt' -exec sed -i '' s/.png/.jpg/g {} +`

**Comment by tischi** [comment]
Using `formatOptions best` in fact increases file size!
Using `formatOptions normal` decreases file size on average but also creates sometimes ugly artifacts.

=> probably best to check which figure slow down loading in the `Modules Overview` and only convert those to JPEG

**Comment by manerotoni** [comment]
Is there any reason to do this?

**Comment by tischi** [comment]
The module overview page sometimes loads slowly, but I think it is not a big deal.
