### ISSUE TITLE
Pixels and Calibration

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#28]
@manerotoni

Pixels and calibration (pixel size) are currently inside the same teaching module.

Do you think we should split into two?

**Comment by tischi** [comment]
@manerotoni

I decided to split this up into two modules (pixels and calibration).

**Comment by manerotoni** [comment]
Hello @tischi should we call the module _real world coordinates_  _pixels calibration_. This feel less convoluted.

**Comment by tischi** [comment]
@manerotoni You are talking about the module with the calibration stuff, right?
Maybe: "Real world pixel coordinates" or "Physical space pixel coordinates", not sure you can choose something.

**Comment by manerotoni** [comment]
Sorry my previous sentence was not precise. I would name the module simply _pixels calibration_ instead of _real world coordinates_ . Typically we refer to image calibration when we are talking about pixel size etc.

**Comment by imagejan** [comment]
Hi guys, how about "Spatial calibration"? (also as opposed to "intensity calibration")

**Comment by manerotoni** [comment]
I like "spatial calibration"
