### ISSUE TITLE
Placeholder for exercises and activities

### ISSUE THREAD

**Issue by manerotoni** [NEUBIAS/training-resources#290]
Hi @tischi, @elnazfazeli, @stemarcotti,

in case part of the module is on master but some parts are still missing I suggest following placeholders for activities or exercises:
 * Nothing if you yet do not know what to cover
 * An empty file with appropriate location and name if you know what to cover.

The usage of exercises and activities of other modules as placeholder is confusing. It could be that one does not have the time to finish a module and months later it may be hard to understand why this exercise is in this module.

**Comment by tischi** [comment]
Yes, of course! Please simply go ahead and delete all the wrong placeholders!

**Comment by tischi** [comment]
I added a template module and also there is a script that you can run, e.g.. like this:

`./add_new_module tracking`

https://github.com/NEUBIAS/training-resources/commit/f2fd90d806e26ec71b1ddf85726d1dd4ccdf8113

**Comment by manerotoni** [comment]
Super, this is really useful
