### ISSUE TITLE
Convert concept maps to Mermaid.js

### ISSUE THREAD

**Issue by tobyhodges** [NEUBIAS/training-resources#3]
- [ ] Automated object filtering
- [ ] Distance transform
- [ ] Image feature enhancement
- [ ] Image math
- [ ] Difference of Gaussian
- [ ] Image display
- [ ] Image data integrity
- [ ] Semantic image segmentation using machine learning
- [ ] Object shape measurements
- [ ] Object splitting
- [ ] Pixel data types

**Comment by manerotoni** [comment]
Most of the concept map are converted.
