### ISSUE TITLE
Variables module bug and improvements

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#302]
@manerotoni 

1. Variables should always start with lower case.
2. Maybe also add a `type`, `name` and `value` for the image? (I would use numpy here as an example and not ImageJ).

<img width="318" alt="image" src="https://user-images.githubusercontent.com/2157566/154928639-1f515c6e-41ae-4a5f-a599-89f97679e515.png">

**Comment by manerotoni** [comment]
Good point. I will go through it.

**Comment by manerotoni** [comment]
**TODOs:**
Figure new and update. May be not so cartoony.

Depending on the language variables can have a definition of type or the type is decided at runtime (what is the correct wording for it?)

Introduce string variables

**Comment by manerotoni** [comment]
Is now in the latest PR https://github.com/NEUBIAS/training-resources/pull/363
