### ISSUE TITLE
Definition of convexity

### ISSUE THREAD

**Issue by AnniekStok** [NEUBIAS/training-resources#310]
Hi @tischi ,

I think there might be a mistake in the the measure_shapes module. 
In the activity, it says convexity is defined as:

Convexity = Object perimeter/convex-hull perimeter

However, it seems in MorpholibJ a different definition is used: 

![image](https://user-images.githubusercontent.com/32863964/156928916-7857497e-e967-4a54-8800-2c6f2bafe749.png)

(area object  / area hull)

This would make more sense given the values that I get when I use the 'analyze regions' function. Shall I update this?

**Comment by AnniekStok** [comment]
I actually also don't see a branch for measure_shapes, was this part of another branch?

**Comment by tischi** [comment]
@manerotoni could you please handle this (I think you are the master of this module).

**Comment by manerotoni** [comment]
I take care of this @AnniekStok : Thanks for pointing this out. There are in fact both definitions. I did not check what was implemented in the plugin :-( 

We should just be sure that we discuss the definition that is indeed applied by the plugin.

**Comment by manerotoni** [comment]
The definition using the perimeter will tend to zero if you have a very fractalized object, whereas the area definition by area may remain  exactly the same.

**Comment by manerotoni** [comment]
It really depends on the plugin. Very confusing indeed:
https://sites.google.com/site/learnimagej/plugins/3d-shape

**Comment by AnniekStok** [comment]
Hi @manerotoni 
Thanks for taking care of this! Yes it is indeed confusing that different plugins use different definitions. 
For today, I wrote my name that I can teach this module. However, I am flexible so if you prefer to teach it and I teach another module tomorrow, that is also totally fine me with. Please let me know!

**Comment by manerotoni** [comment]
Is ready to merge in the break of the module.
