### ISSUE TITLE
new Workflow module that also includes seeded watershed

### ISSUE THREAD

**Issue by manerotoni** [NEUBIAS/training-resources#321]
For instance segment cytoplasm using nuclei as seeds

**Comment by tischi** [comment]
@manerotoni do you have data for this?

**Comment by manerotoni** [comment]
I was thinking data from cellcognition package batteries. I guess we need to refer to it. 
![image](https://user-images.githubusercontent.com/3718770/157427997-e1997449-3147-4cbf-a911-db0d24fe9089.png)

**Comment by manerotoni** [comment]
Also https://www.cellpose.org/dataset

**Comment by tischi** [comment]
Great! Do you have the raw data? Can you share it with me?
Shall I work on it or do you want to do it?

**Comment by tischi** [comment]
Oh, I see that should become a workflow..
I thought of adding this to the watershed module itself?

**Comment by tischi** [comment]
But should we teach seeded watershed already in the watershed module? 
Would you have example data for this?
We could use the above data but preprocess it to make it easy. Do you have the data?

**Comment by manerotoni** [comment]
We should teach seeded watershed, I was thinking that one could erode the nuclei until they separate, or even manually place points. 
I am now extracting the full data-set. Should I upload the file in two color?

**Comment by tischi** [comment]
yes, two channel image is good.
I will try to make add a teaching to the watershed module.

**Comment by manerotoni** [comment]
I uploaded the file to the master branch. 
xyc_8bit__tub_h2b_cecog_battery.tif
It comes from  [tubulin_P0037_T00001_Cgfp_Z1_S1.tif](https://github.com/CellCognition/battery_package/blob/master/images/0037/tubulin_P0037_T00001_Cgfp_Z1_S1.tif)

For the workflow one could use a later time point?

**Comment by manerotoni** [comment]
For the segmentation of the tubulin I summed the 2 channels (otherwise you have holes) and a little bit of smoothing. Works quite well.

**Comment by tischi** [comment]
I played with it but there are nuclei entirely missing in the top left....
In fact also in the lower right.
Do you also have an image without that issue?
DAPI staining would be more reliable than H2B.

<img width="1415" alt="image" src="https://user-images.githubusercontent.com/2157566/157495583-517db519-5697-4b38-800b-4ee5e9185f72.png">

**Comment by manerotoni** [comment]
I would crop out a region that does not have this problem. The images are from live cells. So no Dapi.

**Comment by tischi** [comment]
Yes, I have done this. I will work on it.
