### ISSUE TITLE
Add "Key Points"?

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#328]
@manerotoni @AnniekStok @maulakhan a

In [this module](https://neubias.github.io/training-resources/watershed/index.html) I added back the **Key Points** idea, which is there in the original Carpentries material (you have to scroll to the bottom of the page). I feel it could be a good idea to have such a sort of summary. 

What do you think?

**Comment by manerotoni** [comment]
Not sure what to say. 
Some of the key points we have it in the additional text. 
Also we try to emphasise key point in the exercise. 
I feel it a little bit redundant, but it may not harm. I would not do it a necessary feature of a module.

The advantage of key points is that it forces the teacher to formulate essential learning outcomes.

**Comment by tischi** [comment]
OK, let's leave it in as an optional feature.
