### ISSUE TITLE
Review Local Background Subtraction Module

### ISSUE THREAD

**Issue by AnniekStok** [NEUBIAS/training-resources#329]
Hi @tischi , 

I reviewed the local background subtraction module. I think it looks good, but here are some comments: 

1. One of the prerequisites is Image math, but this module does not exist yet (maybe change it to a comment in the module markdown file, so it does not show up in the list?)
2. Motivation: I think it's fine like this, but I had to read the third sentence twice, it is a bit long. A shorter version could be maybe something like: "Provided that the foreground and background intensities fall in different ranges, image filters can be used to measure and correct for the background"
3. In activity 1, there is a different image link in the preface (some_spots_with_uneven_bg) than in the dropdown menu (spots_local_background_with_noise)
4. In the activity 1 GUI, there is rename to 'background' twice, but one of them should be 'input'.
5. I saw that you used a tickbox icon when you cleaned up activity 2 GUI, cool I didn't know that was possible. Maybe if we want to be super consistent, it can also be applied to activity 1 GUI, changing bullet point 'create 32 bit' to tickbox1: create new image, and tickbox2: 32-bit float result.  
6. I also see what you mean now with the double indentation, in activity 2 I did it differently from what you have in activity 1 (shall I fix that?) Also, we are not consistent as to whether or not we use bold font for the ImageJ commands. 
7. Exercise 2: duplicate command in line 4 is not needed (input image is already present and is not overwritten by next command). 
8. Exercise 2: in general, as a student doing this by myself I would appreciate a little more explanation  to the questions asked in the exercise (e.g. why does the median not work well, while it did in other situations, and what exactly does this attribute filtering do? (it is not in the prerequisites). It could also be a link in the 'learn more' section. 

Hope this helps!

**Comment by tischi** [comment]
Thanks a lot!

> One of the prerequisites is Image math, but this module does not exist yet (maybe change it to a comment in the module markdown file, so it does not show up in the list?)

I removed it.

>  Motivation: I think it's fine like this, but I had to read the third sentence twice, it is a bit long. A shorter version could be maybe something like: "Provided that the foreground and background intensities fall in different ranges, image filters can be used to measure and correct for the background"

I changed it. The issue now also is that after adding your activity with the maximum projection, the concept had to become broader in a sense that there are other ways of producing the background image that do not involve spatial filtering.

>   In activity 1, there is a different image link in the preface (some_spots_with_uneven_bg) than in the dropdown menu (spots_local_background_with_noise)

Fixed

>    In the activity 1 GUI, there is rename to 'background' twice, but one of them should be 'input'.

Fixed

>    I saw that you used a tickbox icon when you cleaned up activity 2 GUI, cool I didn't know that was possible. Maybe if we want to be super consistent, it can also be applied to activity 1 GUI, changing bullet point 'create 32 bit' to tickbox1: create new image, and tickbox2: 32-bit float result.

Done

```
 11   - [ Process › Image Calculator... ]
 12     - Image 1 = input
 13     - Subtract
 14     - Image 2 = background
 15     - [X] create
 16     - [X] 32-bit
```

>  I also see what you mean now with the double indentation, in activity 2 I did it differently from what you have in activity 1 (shall I fix that?) Also, we are not consistent as to whether or not we use bold font for the ImageJ commands.

I think that's fine. As long as it is consistent within one module, I think we could just leave it as it is for now.

>    Exercise 2: duplicate command in line 4 is not needed (input image is already present and is not overwritten by next command).  Exercise 2: in general, as a student doing this by myself I would appreciate a little more explanation to the questions asked in the exercise (e.g. why does the median not work well, while it did in other situations, and what exactly does this attribute filtering do? (it is not in the prerequisites). It could also be a link in the 'learn more' section.

Yes, good point. This does not below there. I removed it and made an issue not to loose it: https://github.com/NEUBIAS/training-resources/issues/330
