### ISSUE TITLE
Output saving module

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#339]
@AnniekStok 

I found a couple of issues [here](https://neubias.github.io/training-resources/output_saving/index.html):

- [ ] Motivation: Remove Fiji specific things
- [ ] Activity preface: Remove ImageJ specific things
- [ ] Show activity for: This should only be "ImageJ Macro" (remove GUI)

- [ ] Macro:

`run("glasbey", "display=blob_labels_macro.tif view=net.imagej.display.DefaultDatasetView@541b120b")`

What is the `display` and `view` stuff about? Do we need this? If you don't know please ask on the forum.

- [ ] Macro:

```
roiManager("Save", outputDir + "/blob_ROIset_macro.zip"); // save rois to output directory
saveAs("Results", outputDir + "/blob_results_macro.txt"); // save results file to output directory
saveAs("Tiff", outputDir + "/blob_labels_macro.tif");
```

Does that also work on Windows??
Anyway, I think best practice is replacing "/" with `File.separator`. What do you think?

**Comment by AnniekStok** [comment]
Thank you for the comments @tischi ,

Motivation: updated
Activity preface: updated
Show activity for: updated
display stuff:  you're right, it's not needed. I just copied it directly from the recorder and didn't check if it was needed or not. 
Macro: yes it works on Windows but I agree File.separator is better so I changed it. 
I also found some other typos that I fixed.

**Comment by AnniekStok** [comment]
If you agree with the changes, can you please merge #340? Thanks!

**Comment by tischi** [comment]
Thanks a lot!
There is one more thing, but I am closing this already anyway.
