### ISSUE TITLE
Jekyll automatically rebuilds

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#34]
@tobyhodges @manerotoni

Not an issue, but a comment:

Once you ran `make serve` Jekyll realised if you changed a file and rebuilds the website automatically. This is awesome! 

Maybe we should add this to `CONTRIBUTE.md`?!

**Comment by manerotoni** [comment]
In master [26fb20c](https://github.com/NEUBIAS/training-resources/commit/26fb20c4b33108289c59f79ad72156231f2c3fd3)
