### ISSUE TITLE
Variable names: Fix it exercise

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#370]
@manerotoni 

<img width="500" alt="image" src="https://user-images.githubusercontent.com/2157566/159178759-a26fb1af-5906-45d6-88fa-011a93d9ca9b.png">

I would not say that the variable names are technically wrong, at least they start lower case 😄 

What about:

1. adding one variable with a meaningful name but with upper case, e.g. `FilePath` => Fix: `filePath`
2. adding an explicit statement in the exercise that one should have **meaningful** variable names. Then it would be more clear that `a` and `b` should be fixed.

**Comment by manerotoni** [comment]
Done
