### ISSUE TITLE
Automated object filtering

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#38]
@manerotoni

What should go into this module?

1. I think the main concept is to remove labels from a label mask image, is it?
2. Should we remove "Automated" from the title? For example, in MLJ you can "manually" remove labels: `Plugins › MorphoLibJ › Label Images › Replace/Remove Label(s)`

**Comment by manerotoni** [comment]
Yes I do not like the name automated. You can also merge labels. 
What about:
"Editing of labels/object"

Filtering is misleading as we are not applying a filtering operation.

**Comment by tischi** [comment]
Currently it looks like this:

![image](https://user-images.githubusercontent.com/2157566/102073276-5d88c300-3e03-11eb-97e7-92c45ac0f067.png)


Would you add label merging? I hardly use label merging in practice...
