### ISSUE TITLE
Installation instruction for tools to be used in the course

### ISSUE THREAD

**Issue by manerotoni** [NEUBIAS/training-resources#399]
Create markdown document one per tool (e.g. 1 Fiji/ImageJ, 1 for python/Napari).
Create an _Tool installation_ module that link to the markdown documents
There is also a _setup.md_ on the main landing page that could have the link to the installation module or md

**Comment by stemarcotti** [comment]
working on this!
@manerotoni @tischi should I create a branch here or on my own fork (+pull request)?
(I managed to setup Jekyll so I can build the website locally to test)
Thanks!

**Comment by stemarcotti** [comment]
mission accomplished, I'll keep you posted =)

**Comment by stemarcotti** [comment]
pull request created, any pre-merge feedback welcome!
Thank you =)
