### ISSUE TITLE
gitpod preview does not work

### ISSUE THREAD

**Issue by manerotoni** [NEUBIAS/training-resources#40]
Hello @tischi and @tobyhodges,
using gitpod I managed to view the project, edit it and successfully launch` make serve`.
The Preview/openBrowser does not seem to work. 
You land on a page `https://4000-e535090b-d892-421c-aba2-2843b0d99b88.ws-eu03.gitpod.io/`
with the '/' not found error.
It has something to do with local generated pages and linked page. `make serve`  links locally but the page is not local. There has been a few issue reports about this, but I was not able to find a solution. 

Antonio

**Comment by tobyhodges** [comment]
@manerotoni I've worked on this a bit but so far have only succeeded in making things worse on the GitPod side. Sorry about that. I will take another look later in the week, but I don't have any more time now.
