### ISSUE TITLE
Slice viewing: How to deal with interpolation?

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#409]
ImageJ GUI activity, add:

- Observe that the number of pixels along the z-axis does not match the number of pixels in the original data.
  - Understand that this is due to interpolation to render the image isotropically.

**Comment by tischi** [comment]
In fact, my post above maybe reflects a more general observation that this module also introduces the concept of interpolation for rendering anisotropic data, but it does not do this "officially", i.e. this is not part of the concept map. 

Maybe we could rethink this: either introduce interpolation properly or try to remove it, e.g. using BDV instead of Orthogonal Views for the slice viewing where interpolation in a sense of creating new pixel values is not needed.

**Comment by tischi** [comment]
I am thinking, maybe:

- we remove the concept of channels and time points from this module
  - dealing with multi-channel data feels like it could be an own module, mainly about different modes of color rendering
  - dealing with time lapse data: could also be an own module  
- we totally focus on volume slicing (3D -> 2D)
- we start with an isotropic image (=> everything is easy, pixels are just resorted)
- we show how things get more difficult with an-isotropic data


@AnniekStok @manerotoni @maulakhan what do you think?

**Comment by AnniekStok** [comment]
Good idea! This module is right now quite full with information. I agree with you that breaking it up in smaller modules would help simplify it. Maybe there could be a small introductory module called 'multidimensional data' to just show what microscopy image data can consist of, which is followed by 3 more in-depth modules (XYZ and volume slicing), (CXY and color rendering), and (XYT and challenges/concepts of time lapse data (not exactly sure what to put in here, different time resolutions maybe?)). I'd be happy to help work on these modules.

**Comment by tischi** [comment]
> Maybe there could be a small introductory module called 'multidimensional data' 

Maybe we just add all of this to the digital image basics? So, make it N-Dimensional instead of 2-D?

Or to not make the first one too heavy we structure it like this:

1. 2-D digital image basics 
2. 5-D digital image basics 
3. 3-D volume slicing

**Comment by AnniekStok** [comment]
I could work a bit on this next week. How about I then try to split the Volume Slicing module in 5-D digital image basics and 3-D volume slicing and we see how it looks?

**Comment by tischi** [comment]
Sounds good to me! Thanks for working on this!

**Comment by tischi** [comment]
@manerotoni OK for you ( see above)?

**Comment by AnniekStok** [comment]
Working on this here #488

**Comment by tischi** [comment]
Closing this issue, as the PR mentioned by @AnniekStok has been closed.
