### ISSUE TITLE
Tool installation: move main text to Activities

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#410]
@stemarcotti 

Right now the installation instructions are all described in the main document.

https://neubias.github.io/training-resources/tool_installation/index.html

I think it would be more consistent with the other modules if each installation was one `Activity`.

That would mean that we create on markdown file per installation and link to them from the main module (as we do also for all the other modules).

What do you think? Was there a reason we decided against this?

**Comment by stemarcotti** [comment]
I don't think we discussed the format of this in detail, and as the text was quite short it made sense to have it in the main module at the time. Happy to work on this so that each software goes into a separate activity! (:

**Comment by tischi** [comment]
> Happy to work on this so that each software goes into a separate activity! (:

If you have the time, I think that would make sense. Thank you ❤️

**Comment by stemarcotti** [comment]
please see pull request here https://github.com/NEUBIAS/training-resources/pull/413

I divided the installation instructions into different activities for each platform (ImageJ, Napari and MATLAB). Website built locally and working =)

@tischi
