### ISSUE TITLE
Website build in PR does not work

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#419]
@tobyhodges do you know what this could be due to?
https://github.com/NEUBIAS/training-resources/actions/runs/3282445695/jobs/5405957251

@manerotoni do you remember whether building the website from a PR ever worked?

**Comment by tobyhodges** [comment]
I have no expertise in GitHub actions, but it looks like some of the actions used in the workflows for the site have ceased to exist/been renamed. My guess is that the files in `.github/workflows/` need to be updated to reflect recent changes in https://github.com/carpentries/styles/tree/gh-pages/.github/workflows

**Comment by tobyhodges** [comment]
A heads up that [The Carpentries is currently in the process of transitioning to a completely new lesson infrastructure](https://carpentries.org/blog/2022/01/live-lesson-infrastructure/), which will replace https://github.com/carpentries/styles/ at some point in 2023. When that transition is complete, the old template will not be actively maintained/developed anymore.

**Comment by manerotoni** [comment]
Hi Tischi, 
I got once this or a similar error and I do not remember how I fixed it. I first went back to another branch and checked if it compiled. There is some errors in the branch. 
Normally the PR compiles properly and this is important before you merge.
I can have a look, but till when I am in HD I have no time.

**Comment by tischi** [comment]
Thanks! Turns out that for us simply removing all the R related things in the actions fixes the issue.
