### ISSUE TITLE
Populate modules list

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#42]
@tobyhodges 

Can you point me to the code that populates below `Modules` menu?

I have two questions:

1. I added a new module with the title `Filter objects`, but I cannot see it, any ideas why?
   - https://github.com/NEUBIAS/training-resources/blob/filterObjects/_modules/filter_objects.md
2. Could we make this list alphabetically sorted?

![image](https://user-images.githubusercontent.com/2157566/102083628-2a026480-3e14-11eb-8917-e66a71a190d9.png)

**Comment by tobyhodges** [comment]
The inclusion and order of modules in the site navigation is controlled by the `module_order` parameter in `_config.yml`. You can either add the file slug (the name but without `.md`) to that list in the site config, or remove the whole `module_order` list to revert back to alphabetical ordering of modules.

**Comment by tischi** [comment]
> remove the whole module_order list to revert back to alphabetical ordering of modules.

Does it then auto-fetch all the .md files in the _modules folder?
If so, I would indeed remove the list for now to make it easier to add and rename modules.

**Comment by tobyhodges** [comment]
Yes, that's right
