### ISSUE TITLE
broken internal links

### ISSUE THREAD

**Issue by manerotoni** [NEUBIAS/training-resources#43]
Hello @tischi and @tobyhodges,
I realised that the links are broken now. 
For example in `binarization.md`
```
prerequisites: 
- "[Basic properties of images and pixels](pixels)"
```
leads to a page `training-resources/binarization/pixels` which does not exists.

This code fixes the problem 
```
prerequisites:  
- "[Basic properties of images and pixels](../pixels)"
```

It is meant to be like this? 

Antonio

**Comment by tobyhodges** [comment]
This is a commonly-encountered problem with page paths differing between local versions of a site (where the site home page is the root of the URL e.g. `localhost:4000`) and the GitHub Pages version, which serves the home page from a subpath i.e. `https://<user_or_org_name>.github.io/<repo_name/`. The way to get around it is to use the `page.root` variable in your relative link paths, e.g.

```
prerequisites: 
- "[Basic properties of images and pixels]({{page.root}}/pixels)"
```

This may need addressing in a few different places, please ping me in an issue whenever you encounter this problem and can't fix it quickly yourself.

**Comment by manerotoni** [comment]
Thanks. I noticed also the issue in the rendered pages on github.io

**Comment by tobyhodges** [comment]
On closer inspection, this specific example seems to be a case of the Pixels module page not being built. There must be something wrong with the YAML in `_modules/pixels.md`...

**Comment by tobyhodges** [comment]
Good news and bad news. I was wrong about the Pixels page - it is being built just fine. But the `{{page.root}}` approach doesn't work because variable substitutions are not handled inside the YAML header. So you will need to write these internal links `../pixels/`, making sure to include that trailing slash at the end.
