### ISSUE TITLE
Extract module activity prefaces into markdown files

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#444]
@tibuch @grinic 

I hacked a bit and got as far as finding

```
sed -n '/^activity_preface: |/,/^activities/p' _modules/pixels.md | tail -n +2 | sed '$d' > pixels_activitiy_preface.md
```

to automatically extract the activity preface part of a module.md into a file 🤓 

Maybe could save us some work...

**Comment by tischi** [comment]
@grinic Did we merge this? If so, could you please close the issue?

**Comment by grinic** [comment]
Yes we merged, going to close it now!
