### ISSUE TITLE
Exercise preface: Auto threshold 

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#449]
This needs to be reworked:

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/2157566/206696211-82e3d230-2af4-4239-92be-56e627f87166.png">

I think we should remove the notion of _not_ taking the histogram of the whole image. One should always take the whole image.

@manerotoni  do you agree?

**Comment by manerotoni** [comment]
@tischi 
I agree. Although the exercise reads such that you only do the histogram of the whole 3D stack. 
Suggestion
* Open xyz_8bit__nuclei_auto ....
* Make sure that the histogram for auto threshold is computed for the whole 3D stack
* Select any threshold method and observe the differences in segmentation

I wonder if for teaching purposes we should not explain mathematically at least one algorithm. Like further explanations in case you want to go into details. It is an unsupervised classification task.
