### ISSUE TITLE
Activity image file formats: python implementation

### ISSUE THREAD

**Issue by grinic** [NEUBIAS/training-resources#451]
AICSImage supports tif, lif and czi.
It can not handle the other image file format types given in the activity (ics, ids, xml, h5).

**Comment by tischi** [comment]
@grinic also not if you add the bioformats_jar ?!

**Comment by grinic** [comment]
Nope, the importer does not complain, but when I try to access the image data and the metadata it throws this error:

```
XMLSchemaValidationError: failed validating 'XMLAnnotation:0' with XsdPatternFacets(['(urn:lsid:([\\w\\-\\.]+\\.[\\w\\-\\.]+)+:Annotation:\\S+)|(Annotatio...']):

Reason: attribute ID='XMLAnnotation:0': value doesn't match any pattern of ['(urn:lsid:([\\w\\-\\.]+\\.[\\w\\-\\.]+)+:Annotation:\\S+)|(Annotation:\\S+)']
```

This happens for both ics/ids and xml/h5 dataset.

**Comment by tischi** [comment]
I think you could raise issues directly here: https://github.com/AllenCellModeling/aicsimageio
What do you think?

One pattern that I see here is that those are both multi-file fileformats:

- ics/ids
- xml/hdf5

Maybe they do not support this? As said I would raise an issue in the above repo. Could you do it?

**Comment by grinic** [comment]
I will raise the issue.
Btw, it does work with ics/ids, I had to change slightly the `load_from_url `function to download the other ids file.

**Comment by grinic** [comment]
I opened an [issue](https://github.com/AllenCellModeling/aicsimageio/issues/454) on the aicsimageio repo.
It seems a similar [error](https://github.com/AllenCellModeling/aicsimageio/issues/195) was previously encountered (and fixed) for a dataset acquired using micromanager.
Do we know how our dataset was created? Micromanager or LabView software? This might help the aicsimageio developers to come up with a fix.

**Comment by tischi** [comment]
- xml/hdf5: Fiji: `Plugins › BigDataViewer › Export Current Image as XML/HDF5`

**Comment by tischi** [comment]
@grinic Do you have a branch for this work? Could we make a PR?

**Comment by grinic** [comment]
I created a draft PR, the issue with image import using aicsimageio (see the [issue](https://github.com/AllenCellModeling/aicsimageio/issues/454) I opened) is not solved though and last I heard is that it worked fine on linux systems, but not on windows. Sorry I don't have much time these days, but I will try to have a go again next week!

**Comment by tischi** [comment]
To be honest, I got distracted with other stuff today and probably also will not work on it.
But if we could try to merge something next week it would be great.
It does not have to work for all the file formats in the activity, if it just works for some that is fine as well.

**Comment by tischi** [comment]
Closing this in favour of the above PR.
