### ISSUE TITLE
issue with tool installation on windows

### ISSUE THREAD

**Issue by grinic** [NEUBIAS/training-resources#456]
I had a problem on several windows machine when following the installation for skimage napari. The OpenJDK installation was not recognized in the environment and this messed up the conda path variables.

Seems that it is solved by installing openjdk explicitly before bioformats_jar:
6. conda install -c conda-forge openjdk=11.0.8
7. conda install -c conda-forge bioformats_jar

I will update the tool installation later to include this special case and PR if ok?

**Comment by tischi** [comment]
@grinic yes, please update it.
