### ISSUE TITLE
Website does not build anymore

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#459]
@tobyhodges @unode,

It seems that the github actions need some changes.

This line https://github.com/NEUBIAS/training-resources/blob/87146098e3d53f327e6da4f364e23bcc2d25ac93/.github/workflows/website.yml#L15

Errors with https://github.com/NEUBIAS/training-resources/actions/runs/3946696973/jobs/6754697829

Do you have any insights how to fix this?

**Comment by tobyhodges** [comment]
Closed by [3f18d70](https://github.com/NEUBIAS/training-resources/commit/3f18d702f2d4753bc37f9767f36403bb2510ebab)
