### ISSUE TITLE
ImageJ/Fiji LUTs 

### ISSUE THREAD

**Issue by SakuSakuLab** [NEUBIAS/training-resources#475]
It is also important to avoid red LUT for those who are red-blind people.
We use magenta LUT instead.

**Comment by SakuSakuLab** [comment]
What I noticed about the NEUBIAS training resource

I’m Yusaku Ohta.

This resource, the NEUBIAS training resource, is really great, very informative.

I thought I knew these things very well, but when I actually tried them, there were a lot of things I didn't understand, and it's very useful.
Especially, plugins like morpholibJ and clij are really useful and I will use them a lot for bioimage analysis from now on.

I have listed below what I was concerned about and what should be added.
I will gladly edit these modules and create new modules if you allow me to do so. I am confident that I can make these modules even better.


[Lookup tables](https://neubias.github.io/training-resources/lut/index.html)
It's also highly recommended to use the exact same color mapping for images that’re acquired on the same day and with the same microscope settings.

Multicolor lookup tables such as heat map, and fire, are also a good way to bring out small differences in the image, such as the FRET and FLIM image where images might have a narrower numerical range so that people understand the subtle differences across that range by multicolor LUTs.

It's important to avoid the red lookup table for those who are red-blind and use the magenta lookup table instead.


[Data types](https://neubias.github.io/training-resources/datatypes/index.html)
8 bit and 16 bit images do not perform calculations correctly if they involve negative values or decimal points in the answer.
The big problem here is that all software does this calculation without warning us.

Image data types
You write "unsigned N-bit integer images can represent values from 0 to 2^(N-1)".
I think this formula is wrong and we don’t need parentheses in this formula.
For example, if N equals 8, then 2 to the power of seven equals 128, but 2 to the power of eight equals 256. So we don’t need these parentheses.


[Image file formats](https://neubias.github.io/training-resources/image_file_formats/index.html)
We have to note that converting file formats results in a loss of information. For example, saving a TIFF image as a JPEG changes the image dimensions, data type, pixel values, and metadata.
And that means we can't get back our raw data here.
Therefore, to re-save images for quantitative image analysis, we should choose a lossless compression file format like TIFF.
It's a fairly old file format. But it supports both 8, 16 and 32 bit images and grayscale or RGB, which is nice because we work with them.
It supports lossless compression, which is also nice because we don't want to use lossy compression.


[Segmentation](https://neubias.github.io/training-resources/segmentation/index.html)
Image segmentation is the process of partitioning an image into objects or regions, which is required for the measurements of features such as intensity, area, volume and so on.
So it’s really important in bioimage analysis.

Semantic segmentation divides images into regions of the same category, for example, Endoplasmic reticulum, mitochondria, cytoplasm and so on.
It’s implemented in Fiji as a plugin such as Trainable weka segmentation.
Instance segmentation ,on the other hand, divides images into individual objects, for example, “nucleus No.1”, “nucleus No.2”, “nucleus No.3”, and so on.
It’s also implemented in Fiji as a plugin such as StarDist.


[Auto Thresholding](https://neubias.github.io/training-resources/auto_threshold/index.html)
Many different algorithms basically work by assuming that our image is made up of background pixels and foreground pixels and that they are both roughly Gaussian distributed and they basically look for the minimum between those two distributions and then set the threshold there.


[Global background correction](https://neubias.github.io/training-resources/global_background_correction/index.html)
Exercises No.2
I think line 19 of this code is wrong.
run("Intensity Measurements 2D/3D", "input=intensity labels=labels mean max numberofvoxels");
->
run("Intensity Measurements 2D/3D", "input=xy_16bit__nuclei_with_background.tif labels=labels mean max");


[Neighborhood filters](https://neubias.github.io/training-resources/filter_neighbourhood/index.html)
The larger the filter size, the worse the spatial resolution of the image.
For example, two nearby cell nuclei will be touching together.
That's why we want to keep the filter size as small as possible.

**Comment by SakuSakuLab** [comment]
About the training course in Okazaki

In January of this year, I gave a training course on image analysis (2 sets of 80 minutes each).

The first half of the training covered the basics of using Fiji, such as opening an image file, zooming in and out, adjusting contrast, measuring, using the scrolling tool and the ROI manager, etc. 

The second half is simple image analysis workflows using FIJI. In my experience, students get bored with just the basics of image analysis using FIJI, so I added workflows in the second half. The workflows are to count the number of cell nuclei manually, semi-automatically and fully automatically. Semi-automatic counting is a traditional image analysis, i.e. creating a binary image with a certain threshold and counting the number of objects that have an area greater than a certain threshold. Fully automatic counting is done using a deep learning based segmentation plugin called Stardist.

This training covers Digital Image Basics, Lookup Table, Segmentation, Threshold, Object Shape Measurement, and Watershed in [your modules](https://neubias.github.io/training-resources/all-modules/index.html).

The training was given in two 80-minute sessions, which was enough time to teach slowly, but not enough time to explain in detail how to use deep learning and the Stardist plugin.

The training course was aimed at Masters and PhD students who were not familiar with image analysis, but they were able to easily understand the content of the training course.

Based on this experience of mine, I propose the following plan.


Day 1
[the Image Analysis topics](https://globalbioimaging.org/international-training-courses/abis-gbi-2023-course)
- Handling images
- Segmentation and Thresholding

Morning (2 sets of 90 min each?) 
contents - Basics of using Fiji, Digital Image Basics, Lookup Table, Segmentation, Threshold, Object Shape Measurement, Spatial Calibration, Data Types and Watershed

workflows - Counting cell nuclei (i.e. creating a binary image with a certain threshold and counting the number of objects that have an area greater than a certain threshold)

Afternoon (2 sets of 90 min each?) 
contents - Neighborhood Filtering, Object Intensity Measurement, and Global Background Correction.

workflows - [Nuclei segmentation and shape measurement](https://neubias.github.io/training-resources/workflow_segment_2d_nuclei_measure_shape/index.html)
workflows - [2D noisy object segmentation and filtering](https://neubias.github.io/training-resources/workflow_segment_2d_noisy_nuclei_filter_objects_measure_shape/index.html)

Each of these modules is very important.
But I think students will get bored if we just do each module in detail; I don't think we should spend that much time on each module, and it's easier for them to understand the importance of each module if they work through the workflows.

It would be a good idea to give students [the links to these modules](https://neubias.github.io/training-resources/all-modules/index.html) after the training so that they can review and understand much more detail about these modules on their own.

I have also given lectures on the basics of image analysis as well as the training course, so I believe I can adequately teach the above topics.

Of course, we don't know at this point how long it will actually take, so we'll have to adjust later.

This corresponds to Handling images, and Segmentation and Thresholding in [the Image Analysis topics](https://globalbioimaging.org/international-training-courses/abis-gbi-2023-course).

The remaining one day of the training course in Okazaki can cover the remaining [image analysis topics](https://globalbioimaging.org/international-training-courses/abis-gbi-2023-course): Registration and Stitching and Visualization. In addition, other image analysis workflows can be performed using Fiji plugins developed by Dr. Ignacio, such as the registration plugin called bUnwarpJ and the semantic segmentation plugin called Trainable weka segmentation. Dr. Ignacio can decide the details of the second day as he wants.

Day 2
[the Image Analysis topics](https://globalbioimaging.org/international-training-courses/abis-gbi-2023-course)
- Registration and Stitching
- Visualization

modules? - Slice viewing, Projections, Volume rendering, Image file formats, , , , , ,

workflows? - workflows using Fiji plugins developed by Dr. Ignacio, such as the registration plugin called bUnwarpJ and the semantic segmentation plugin called Trainable weka segmentation. Dr. Ignacio can decide the details of the second day as he wants.


These are what I think.

P.S. I don't think it is necessary to tell the participants about [your modules](https://neubias.github.io/training-resources/all-modules/index.html) in advance. This is because there will be a difference between those who have studied the modules in advance and those who have not. It would be good to tell it later to review the training course.

**Comment by tischi** [comment]
done here: https://github.com/NEUBIAS/training-resources/pull/481
