### ISSUE TITLE
Move detailed module explanations elsewhere

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#476]
@manerotoni @stemarcotti @AnniekStok 

For some modules we have a lot of text, e.g. here:

https://neubias.github.io/training-resources/lut/index.html

I would like to remove this from the main site and just link to it (into a markdown) to reduce visual clutter.

What to you think?

Long term we can think of an even better solution but right now, as a teacher, I find it mainly distracting to have so much text.

**Comment by manerotoni** [comment]
Hell @tischi, 
personally I do not think it is a problem.  I hate to click on yet another page to get more explanations.  It is not a poster so I think it is fine to have additional info after the short figure. You do not have to teach the details if you do not need yet. 
 For LUT I do in fact always skip the part on contrast etc. 

I think a solution would be to have dropdown menus that open when you click on this extra information.  Nothing I want to do in the near future, There are more important tasks to do.

**Comment by manerotoni** [comment]
But why should you tell **not** to use a lot of stuff? 
A teacher can use the material if they want to.  You can do 1 or 5 activities at the teacher discretion.

I guess anything is fine. A drop-down (something similar we use for solutions) or a link. I was looking at the new update of Pete's book https://bioimagebook.github.io/ .
He uses a few of multitab/dropdown stuff.

**Comment by tischi** [comment]
My point is, that if you are a beginner and see this material for the first time, it currently for some modules is overwhelming and bit hard to find the (currently) essential stuff, namely the Activities.

Also, for many modules we do not have any extra text and thus the overall impression is quite inconsistent.

**Comment by manerotoni** [comment]
May be we should have the order of the module changed?
Motivation
Slides
Activities
Additional info
Further reading etc.
