### ISSUE TITLE
Change output of open_ij_tiff when calibration is missing

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#512]
```
Y scale is missing from the tiff file !!!!!
Y scale was assigned '1' and y scale unit was assigned 'Pixel'
X scale is missing from the tiff file !!!!!
X scale was assigned '1' and x scale unit was assigned 'Pixel'
```

Maybe this is sufficient and more concise?

`x scale missing; setting to: 1 pixel`
`y scale missing; setting to: 1 pixel`

you could change this directly in the master branch.

**Comment by manerotoni** [comment]
Make it one comment for the whole image
`some dimension scales are missing; setting scale to 1, and unit to Pixel `

**Comment by tischi** [comment]
or just: `scaling missing; setting to 1 pixel`
