### ISSUE TITLE
Tool installation layout

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#518]
@manerotoni 

Should we convert the [tool installation](https://neubias.github.io/training-resources/tool_installation) to the new multi-activities layout? 

Pro: This would give us linkable headings, which I think would be very convenient.

Con: I am just not sure about the granularity, because the: "choose platform" does not make sense....

**Comment by tischi** [comment]
I would like to refactor it to the multi-activities, because for skimage napari we will in fact have two platforms: "own computer", "BAND".

I will just go ahead.

**Comment by manerotoni** [comment]
Will BAND be EMBL specific or could we also piggy back on it. I can generate VM for us.

**Comment by tischi** [comment]
BAND won't be EMBL specific. We just have to make sure that we have enough resources, but I think it will be fine...
