### ISSUE TITLE
Slice viewing..

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#540]
Hi @AnniekStok,

I think @manerotoni already started moving some of the content from our current [slice viewing](https://neubias.github.io/training-resources/volume_slicing/index.html) module into the [digital image basics](https://neubias.github.io/training-resources/pixels/index.html).

Please coordinate with him!

I think we all agreed that:

1. slicing through time and channels could be part of digital image basics
2. slicing (at arbitrary angles) through a volume should be part of the "slice viewing"

Thus, I'd say:

- [ ] Rename "Slice viewing" to "Volume slicing"

**Comment by manerotoni** [comment]
Hello,
I merged the Digital image basics with the multi-dimensional activities. This should help sort out what is missing.

antonio

**Comment by manerotoni** [comment]
Hi @tischi and @AnniekStok,
the main reason of adding in the Digital image basics some Multi-dimensional images is that in Napari loading 5D images requires some specification (in ImageJ thanks to the metadata automatically read in, this is rather trivial).
I feel that this is quite important as users would like to be able to visualize images in a tool and you need a few commands for it. In the module nothing happens apart assigning the dimensions correctly and looking at the data. 

This material could be moved to a multi-dimensional module (as the one you are creating??). This would make the module a little lighter. In this case such a module should be taught within the next python course. 

Antonio

**Comment by AnniekStok** [comment]
Yes I made a draft pull request here (#488) a while ago to split the slice viewing module into N-dimensional image basics and volume slicing and subsetting. I think there might be some overlap now between 'digital image basics' and 'N-dimensional image basics' so maybe we don't need 'N-dimensional image basics' anymore, or we can combine them into a single module. I included napari examples but I see you also did that so they are probably quite similar.

**Comment by manerotoni** [comment]
Hi,
I was not aware of it and was in an active editing mode. 
My suggestion is that if you bring the PR for review (currently there some conflicts in  you PR that need to be solved first). I look at it and may be we can make a good decision together. I think having two basics module is fine.
Antonio

**Comment by AnniekStok** [comment]
Hi, 
yes, I think those conflicts only appeared just now; I have resolved them and marked the pull request as ready for review.
