### ISSUE TITLE
Spatial Calibration Napari

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#554]
@tibuch @grinic @manerotoni 
I am reviewing the spatial calibration python module and have some issues:

```
# %% [markdown]
# Napari GUI: Change the axes order using the orthogonal views button. \
# Napari GUI: Inspect the volume to check whether the voxel size makes sense.\
# Napari GUI: Use the 3D viewer button to render the image in 3D.
```

1. What is the "orthogonal views button"?
2. I cannot find the 3D viewer button...

<img width="532" alt="image" src="https://github.com/NEUBIAS/training-resources/assets/2157566/5530085d-e33b-412a-bc68-4783f15e06cf">

**Comment by tischi** [comment]
Other question: can one tell napari **not** to interpolate?

![image](https://github.com/NEUBIAS/training-resources/assets/2157566/24197d67-0bc9-4461-9fa2-1a9aad86f14d)


-----

And I also don't understand this instruction:

`# Visualize images side by side in Napari (Orthogonal views)`

What has "side by side" to do with "orthogonal views"?

**Comment by tischi** [comment]
#### Extracting the Point layers

And isn't it possible to directly extract layers by their name?!

```
#%%
# extract point coordinates
layer_names = [l.name for l in napari_viewer.layers]
points2d = napari_viewer.layers[layer_names.index('points2D')].data
points3d = napari_viewer.layers[layer_names.index('points3D')].data
```

Can we do something easier? Maybe:  `napari_viewer.getLayer('points2D')` ?!
(not sure, because auto-completion does not work for me in Visual Studio Code....)

**Comment by tischi** [comment]
#### Inspection points

I think it would be good to add some print statements, like below:

<img width="1219" alt="image" src="https://github.com/NEUBIAS/training-resources/assets/2157566/bc1f9889-32ef-4d6a-a5f5-0a80ef6e24af">

However, I don't understand what the `4.` is about...?

**Comment by tischi** [comment]
#### Measuring point distances

In the current code, it looks as if even thought the image was adding with its voxel size to the viewer, the `Points` are still in pixel units?! This would **not** be **obvious** and should be mentioned explicitly in the material (e.g. I think ImageJ does behave differently in this respect). If that is true I will add a comment.

@grinic do you know?

**Comment by grinic** [comment]
Hi @tischi.

> What is the "orthogonal views button"?
> I cannot find the 3D viewer button...

I have added the names of the buttons in the markdown (`change order of visible axes` and `toggle ndisplay`).

> Other question: can one tell napari not to interpolate?

it's by default not interpolated, the dimension that seems interpolated is the X axes. It looks interpolated because there are many more pixels than in the Z dimension.

> What has "side by side" to do with "orthogonal views"?

Corrected (it's `toggle grid mode` button)

> And isn't it possible to directly extract layers by their name?!

You are right, it's actually possible to extract directly with the layer name with
`points2d = napari_viewer.layers['points2D'].data`

I have pushed into #555 the updates up to this point.

**Comment by grinic** [comment]
> In fact, I think this is too complex for teaching, as there are a lot of new concepts. Is it OK if I change this to drawing only 2 points in one layer (I have a strong feeling that this is better in order not to overload the students)?

The idea was to show that one has to be careful computing distances with points in 3D due to anisotropy in the image. I don't have a strong opinion about this, happy to remove the `points3D` and call `points2D` -> `points_within_slice`

**Comment by tibuch** [comment]
If you think it will overload the students I would follow your gut-feeling since you have more experience than I have :nerd_face:

**Comment by tischi** [comment]
@grinic @tibuch is it correct that the "scale" is only applied to the "stretch" visualisation but does not change the voxel coordinates?!

**Comment by tibuch** [comment]
Not sure if I understand. The underlying data is still in the integer-coordinates (matrix indices). Do you mean the point-coordinates returned by the point-layers? This I have to double check.

**Comment by grinic** [comment]
The points coordinates are still in matrix indices. 

That is a bit confusing because when using `scale` in the `napari_viewer.add_image`, the coordinates that appear at the bottom left are the calibrated ones, but when using `napari_viewer.layers['Points'].data` the returned values are matrix indices.

**Comment by tibuch** [comment]
I think this would give the proper coordinates:
`viewer.layers['Points'].data * viewer.layers['Points'].scale`

**Comment by grinic** [comment]
Yes. So the activity could be:
- draw 2 points (either in plane or in different planes)
- compute distance using `viewer.layers['Points'].data`
- compute distance using `viewer.layers['Points'].data * viewer.layers['Points'].scale`
- discuss why these numbers are different, and 
- appreciate that one needs spatial calibration to have distances in physical units

Would that work @tischi? I can update the activity in #555

**Comment by manerotoni** [comment]
Hi,
I wonder if one could split  the first activity in 2. It is now very long with a lot of code. 
One where you apply the calibration to the image. The other where you place points and measure.

**Comment by manerotoni** [comment]
> 



> @grinic @tibuch is it correct that the "scale" is only applied to the "stretch" visualisation but does not change the voxel coordinates?!

Yes. In fact in the activity the distance are computed within python by multiplying with the scales.


```
# %%
# compute distance between 2D points in voxel indices
dist_2d_pxl = np.sqrt(((points2d[1]-points2d[0])**2).sum())
print('Distance in pixels:',dist_2d_pxl)

# %% 
# calibrate point position and compute distance in um 
points2d_cal = np.stack([p*voxel_size_input for p in points2d])
# compute distance between points in um using calibrated point positions, appreciate that these are different values!
dist_2d_cal = np.sqrt(((points2d_cal[1]-points2d_cal[0])**2).sum())
print('Distance in um:',dist_2d_cal)
```

**Comment by grinic** [comment]
Either solutions works well for me, but I understood @tischi wants to remove the 2D/3D examples, and only keep one. In that case, the activity would be shorter. Basically:
```
# %%
# extract point coordinates
points = napari_viewer.layers['Points'].data

# %%
# compute distance between points in voxel indices
dist_pxl = np.sqrt(((points[1]-points[0])**2).sum())
print('Distance in pixels:',dist_pxl)

# %%
# extract point calibrated positions
points_cal = napari_viewer.layers['Points'].data * napari_viewer.layers['Points'].scale

# %%
# compute distance between points in um using calibrated point positions
dist_cal = np.sqrt(((points_cal[1]-points_cal[0])**2).sum())
print('Distance in um:',dist_cal)

# %% [markdown]
# - discuss why dist_pxl differs from dist_cal
# - appreciate that one needs to use spatial calibration to obtain distances in physical units
```

**Comment by manerotoni** [comment]
> Either solutions work well for me, but I understood @tischi wants to remove the 2D/3D examples, and only keep one. In that case, the activity would be shorter. Basically:

Good idea. I guess it is enough to do only 3D points.

**Comment by grinic** [comment]
This should be ready to merge in #555.

**Comment by tischi** [comment]
@grinic 
Thanks for the changes! 
Closing this issue in favour of https://github.com/NEUBIAS/training-resources/pull/555
