### ISSUE TITLE
workflow 2d segmentation: define function?

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#565]
@grinic @tibuch 

I thought we concluded that we don't want to define a function here?

<img width="996" alt="image" src="https://github.com/NEUBIAS/training-resources/assets/2157566/f7112ce5-c43c-4061-b0f0-5f87a9c3d9e7">

**Comment by grinic** [comment]
That discussion was for the workflow for noisy 2D segmentation, day3. It makes sense to use the same in both workflows though

**Comment by tischi** [comment]
I will remove the function now...

**Comment by tischi** [comment]
Done via [Improve segment_2d_nuclei_skimage_napari.py](https://github.com/NEUBIAS/training-resources/commit/5b46703648035746fe584fce9650752b5c6d1287)

(@grinic if you have time it would be nice to add some text/link that explains the pandas stuff)
