### ISSUE TITLE
markdown activities still supported as well?

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#57]
@tobyhodges @manerotoni 
We just discussed that in the activities folders would be just plain text scripts, like `binarise.py`.
However I found this one: https://github.com/NEUBIAS/training-resources/blob/master/_includes/binarization/activities/binarization_knime.md
Would that still work?

**Comment by tobyhodges** [comment]
Yes. I will factor this in when adjusting the layout to allow syntax highlighting.

**Comment by manerotoni** [comment]
Also the GUI can't be plain text script
