### ISSUE TITLE
Module Nuclei 2D segmentation and shape measurement Typos in code

### ISSUE THREAD

**Issue by manerotoni** [NEUBIAS/training-resources#571]
The code of https://neubias.github.io/training-resources/workflow_segment_2d_nuclei_measure_shape/index.html has a lot of typos and bugs.

I will fix them tonight. Now it is in fact quite fun to find the errors with the students. They learn something.

**Comment by tischi** [comment]
I can also fix them now. Let me know...

**Comment by grinic** [comment]
Beautiful, we are loving the activity :)

![image](https://github.com/NEUBIAS/training-resources/assets/45073015/5da5d426-820d-419d-8933-d76cbef61d0a)

**Comment by manerotoni** [comment]
Fixed in #573, just need to merge.
