### ISSUE TITLE
Change location of Home button

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#602]
<img width="608" alt="image" src="https://github.com/NEUBIAS/training-resources/assets/2157566/26ea15f1-1d89-491c-9ab0-7e1b9a6a04fb">

@tobyhodges do you know where I could change to which site the Home button points?

**Comment by tobyhodges** [comment]
The link target is set on line 38 of `_includes/navbar.html`. Make sure you provide users with another way to easily return to the landing page of the lesson, though, if you are going to point this button to somewhere else!

**Comment by tischi** [comment]
Thanks @tobyhodges !

Do you also know where `{{ relative_root_path }}` is defined?

I am asking because I would eventually like to fix this: https://github.com/NEUBIAS/training-resources/issues/601

**Comment by tobyhodges** [comment]
It is set in `_includes/base_path.html` but that file is... not the easiest to comprehend

**Comment by tischi** [comment]
Thanks!

For the other question: 

`<a class="navbar-brand" href="{{ relative_root_path }}{% link all-modules.md%}">Home</a>` is probably what I need.
