### ISSUE TITLE
Binary operations

### ISSUE THREAD

**Issue by manerotoni** [NEUBIAS/training-resources#61]
Hello @tischi,
I think we should have a module for binary operations. The question is if we should keep it in one module or several modules. 

Rank filtering gives erosion (min) and dilation (max) a combination of the two is closing or opening depending on the order.

Outline is a convolution filter (edge detection)

What is fill holes? In ImageJ is it a connected component of the background?

Should we do 3 modules or one big module? In a way we explain all concepts separately so one could do one module that uses 3 previous modules.

**Comment by tischi** [comment]
I think my logic in my old material was:

1. Introduce "Rank Filters" as one concept
2. Introduce "Rank Filter Sequences" as another concept (open, close, inner edge, outer edge, ...)

Would that work for you?

> Outline is a convolution filter (edge detection)

Not necessarily, you can also do it with rank filters:
```
inner_edge = im - min( im, radius = 1 );
outer_edge = max( im, radius = 1 ) - im;
```

> What is fill holes? In ImageJ is it a connected component of the background?

Good question! I have never introduced it, probably technically indeed a connected component?!

**Comment by manerotoni** [comment]
I will still call it binary operations, this is how people usually name it. We can present it as a sequence of rank filters. 

If we introduce edge detection filter one can have an exercise as applied to a binary. I wonder if it is then the inner or outer edge.

The connected components of background could be a nice way to explain the fill holes operation. One could have an exercise on this. May be not for the course.

The nice thing is that one can add more exercises as you go.

**Comment by tischi** [comment]
> If we introduce edge detection filter one can have an exercise as applied to a binary. I wonder if it is then the inner or outer edge.

For the morphological (rank filter based) edge detection I think we should teach both, it depends on the use case. One can also have an edge that this two pixels thick:

`edge = inner_edge AND outer_edge`  :-)

I think other types of edge detection like Sobel, Canny and what not, should rather to the convolution filters (or have their own module, because some of them are more complex).
