### ISSUE TITLE
raw data for figure missing

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#611]
@manerotoni @AnniekStok did one of you create the figure for this module?

https://neubias.github.io/training-resources/measure_shapes/index.html

I cannot find the corresponding powerpoint slides, which should be in the `figures/resources` folder, which I would need to adapt it to also include the possibility of using ROIs for shape measurements.

**Comment by AnniekStok** [comment]
Sorry, I didn't make it and don't see it in the folder either unfortunately.

**Comment by tischi** [comment]
Oops, based on the commit history, it was me that added this figure ;-)
