### ISSUE TITLE
Volume slicing: Remove subsetting and put more emphasis on anisotropy

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#613]
Hi @AnniekStok @manerotoni @maulakhan @tibuch @grinic et al.,

Would it be OK for you if, for the [volume slicing module](https://neubias.github.io/training-resources/volume_slicing/index.html), I would

1. Remove the "subsetting" part of the Figure? I don't think it fits here, because I think that subsetting (aka cropping) is nothing that is specific to volumetric data.
2. Put much more emphasis on anisotropy! I think this is the biggest conceptual challenge in volume slicing and right now is only mentioned inside the activity implementations.
3. For simplicity, just use single colour images in the activities? I think having multi-colour here will distract the students attention having to deal with channel sliders and LUTs.

I think this DNA metaphase plate would be a quite nice example image:

<img width="670" alt="image" src="https://github.com/NEUBIAS/training-resources/assets/2157566/8808c873-b8e4-4cbd-81da-fb52c4c95924">

from: https://pubmed.ncbi.nlm.nih.gov/34787651/

What do you think?

**Comment by AnniekStok** [comment]
Yes sounds good! I can also help if needed as I think I worked on part of this one before.

**Comment by tischi** [comment]
Thanks @AnniekStok! I think the fastest is if I just do something and then ask you to review it.

**Comment by tischi** [comment]
@AnniekStok I tried to modify the figure but the powerpoint drawings are not editable. 

<img width="519" alt="image" src="https://github.com/NEUBIAS/training-resources/assets/2157566/b8ce5848-56d4-4244-aea9-c6745f4ab6ea">

Do you have an editable version of this? 

E.g., 

1. I discussed with @maulakhan that it would be good to also add some random numbers in the currently empty voxels of the extracted slices.
2. Maybe, for simplicity, we should remove the right part, where the extracted slice is rotated? In fact, I am anyway not sure that the position where the voxel with the value `1` ends up is where it typically would end up. 
3. We should come up with something do illustrate anisotropic voxels, do you have a suggestion?

**Comment by AnniekStok** [comment]
I believe @stemarcotti created this figure, and put the pptx file here: https://github.com/NEUBIAS/training-resources/files/7896791/20220118_slicing.pptx

Adding random numbers would make it clear that those pixels are not really empty, but that we just focus on the colored ones. 

I think the rotation was there to make it clear that you have to rotate the image to see it on the 2D screen. Maybe we can visualize that somehow? 

For anisotropic voxels, maybe we can just use elongated rectangles instead? E.g. (raw sketch):
![image](https://github.com/NEUBIAS/training-resources/assets/32863964/17874fb1-9364-4273-a597-25aa22179d95)

**Comment by tischi** [comment]
Thanks! The PPT you found is editable! I will copy this into the `volume_slicing.pptx`.

I simplified the figure now:

<img width="525" alt="image" src="https://github.com/NEUBIAS/training-resources/assets/2157566/97cccad2-134f-4965-bf42-976b230113b1">

In BDV they are not squished, but rendered exactly as you depicted it.

<img width="912" alt="image" src="https://github.com/NEUBIAS/training-resources/assets/2157566/11e2538e-c087-4d82-a480-6ca79021a488">

So maybe, we could just have the above figure that @stemarcotti created but with anisotropic voxels? Then we would need only one drawing to show everything?

**Comment by tischi** [comment]
In your sketch, I would rather elongate along the axis that runs from top to bottom...as I would find it more intuitive that that is the z-axis...

**Comment by AnniekStok** [comment]
Ok, sounds good! I can quickly remake it to have one like the updated one from @stemarcotti you just showed but with elongated voxels vertically?

**Comment by tischi** [comment]
Thanks, that would be great! Are you using PPT? This would be important for compatibility.

**Comment by AnniekStok** [comment]
Illustrator, but the shapes are pastable in powerpoint so I can convert it for compatibility.

**Comment by AnniekStok** [comment]
This one should be editable (maybe we want to remove the 3d shapes in between and only show the flat one):
 [volume_slicing.pptx](https://github.com/NEUBIAS/training-resources/files/14095878/volume_slicing.pptx)

**Comment by tischi** [comment]
Thanks! Yeah, let's remove the shapes in-between. And could you make all the voxel size number letters the same size? I think it would look more beautiful.

**Comment by AnniekStok** [comment]
[volume_slicing.pptx](https://github.com/NEUBIAS/training-resources/files/14096725/volume_slicing.pptx) like this?

**Comment by tischi** [comment]
In powerpoint it renders a bit weird:

<img width="640" alt="image" src="https://github.com/NEUBIAS/training-resources/assets/2157566/a2b27e0d-9065-4514-8fe7-428e6c7e3130">

- Font size a bit too big
- Strange thicker line between the 3rd and 4th column in the lower grid

Is that something you can fix? Otherwise I can do it.

**Comment by AnniekStok** [comment]
[volume_slicing.pptx](https://github.com/NEUBIAS/training-resources/files/14097860/volume_slicing.pptx)

**Comment by tischi** [comment]
@AnniekStok sorry, the image dimensions (2,4) and (2,3) are missing in the slices; it turns out adding them in PPT is very painful, because, e.g., the arrows are not one object, but several. Could you maybe do the image dimensions in PPT? In general, I think the more of this is done in PPT the easier will it be for future contributors to to further work on this.

**Comment by tischi** [comment]
Thanks! I think now it is good!

**Comment by tischi** [comment]
@AnniekStok 

Could you please review this module: https://neubias.github.io/training-resources/volume_slicing/index.html
And, once we agree on the content, could you please adapt the IJ-Macro implementation to match the GUI implementation ?
I am not sure we need to keep the Groovy or Jython part, I don't see myself teaching this, I think we will mostly teach python once it comes to more serious scripting...what do you think?

**Comment by tischi** [comment]
> I think a python activity slicing in numpy arrays could be nice? 

Of course, do you feel like adding it? You could take some of the other python code in other modules as templates.

**Comment by AnniekStok** [comment]
Yes I can, though not right away since this week is a bit busy. How about a python-napari-gui and a python-napari version (similar to imagej-gui and imagej-macro)?

**Comment by tischi** [comment]
I am closing this issue now, because it has been refactored, but of course feel invited to still add some python implementations :-)

**Comment by AnniekStok** [comment]
A bit late but I have added a proposal for a python-napari implementation in the pull request here: #630
