### ISSUE TITLE
Remove module order 

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#62]
@manerotoni 
I would like to remove the module order from `_config.yml` such that they would be ordered simply alphabetically.
OK for you?

**Comment by manerotoni** [comment]
Fine with me. In fact I merged one of your commits and it did remove the order. Now it is alphabetically.
For the course we can fork and create an order we like.

**Comment by tischi** [comment]
@manerotoni 

Weird, I am building the website from a _config.yml where there is no module order but it looks like this, which is only partially alphabetically ordered:

![image](https://user-images.githubusercontent.com/2157566/102921888-6e81a600-448d-11eb-9a9d-74219edff17a.png)

Do you have any idea why?

Ah, maybe the markdown files have different names than the titles and they determine the order. 

Thus we should probably at some point make this consistent?
