### ISSUE TITLE
pixels_act1: add examples of slicing (to extract a block from an image)

### ISSUE THREAD

**Issue by k-dominik** [NEUBIAS/training-resources#629]
We discussed that adding slicing would give a broader foundation/refresher/introduction into numpy slicing syntax for ndarrays.

https://github.com/NEUBIAS/training-resources/blob/64feb6768703dc2d7fdd90c82ada8425d68255f8/_includes/pixels/pixels_act1_skimage_napari.py#L57-L61

**Comment by tischi** [comment]
yes, something like `image[10:15,20:25]` could be very useful in practice.
