### ISSUE TITLE
Clicking on python files in jupyter will open them to edit, not as notebooks

### ISSUE THREAD

**Issue by k-dominik** [NEUBIAS/training-resources#644]
https://github.com/NEUBIAS/training-resources/blob/b1ddbd8c12e26edaad96c2124777de2b1987446e/_includes/tool_installation/install_skimage_napari_conda.md?plain=1#L17

one needs to right click (tested on all platforms).

**Comment by tischi** [comment]
This is now fixed in https://github.com/NEUBIAS/training-resources/blob/master/_includes/tool_installation/install_skimage_napari_conda.md, is it?

**Comment by k-dominik** [comment]
I haven't checked all the module texts whether they still have the old instructions, so I'm not sure to be honest.
