### ISSUE TITLE
pixels module assessment does not work for python

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#646]
Currently this is the assessment for the pixels module:

```
assessment: >

  ### 2-D image inspection
    Open image
    [xy_8bit__nuclei_noisy_different_intensity.tif](https://github.com/NEUBIAS/training-resources/raw/master/image_data/xy_8bit__nuclei_noisy_different_intensity.tif).
    Hint: For certain exercises the inspection of the histogram will help
    1. What is the value of the pixel at the indices (x=20,y=20)?
    1. What is the highest value in the image?
    1. What is the most frequently occurring value in the image?
    1. Where is this pixel with the indices (x=0,y=0)? Why is this potentially confusing?
    1. How many pixels does this image have in the x direction?
    1. What is the highest pixel index in the x direction?
    1. If you were to rotate the image by 90 degrees, would it change the image histogram?

    > ## Solution
    > 1. 82
    > 1. 129
    > 1. 55
    > 1. Top left; normally x/y coordinate systems have their origin at the bottom left
    > 1. 59
    > 1. 58
    > 1. No, the gray value histogram is independent of the pixel locations
  {: .solution}

  ### 3-D image inspection
    Open image: [xyz_8bit__mri_head.tif](https://github.com/NEUBIAS/training-resources/raw/master/image_data/xyz_8bit__mri_head.tif)
    1. What is the value of the voxel at the indices (x=93,y=124,z=13)?
    1. Which is the highest value in the image?

    > ## Solution
    > 1. 47
    > 1. 255
    {: .solution}
```

The issue here is that the indexing is ImageJ specific; and I do not know how to write this such that this would also work for python. In fact, since we are choosing the location `20, 20` for the "2-D image inspection" it may work for both python and Java since both are 0-based, but this would not work for, e.g. MATLAB.

Maybe we entirely remove this assessment?

Any ideas @manerotoni @k-dominik ?

**Comment by k-dominik** [comment]
hm, I would want people to learn about pixel access...

**Comment by tischi** [comment]
They do learn it in this module; this is the whole point of the module; all the "activities" are about teaching pixel access.

I am just arguing to remove this specific "assessment", because 

1. It will be hard to write this is a completely language agnostic way, because of the indexing issues
2. In fact, I think this is the only module where we have an actual complex task like that as an "assessment"; normally we have just simple questions like: "how many values does a binary image have."

**Comment by k-dominik** [comment]
Right, sorry - makes sense!

**Comment by tischi** [comment]
Thanks! Then I will remove this.
