### ISSUE TITLE
remove line profile from skimage activity in digital image basics module?!

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#650]
I find this really disrupts the flow of teaching: https://github.com/NEUBIAS/training-resources/blob/master/_includes/pixels/pixels_act1_skimage_napari.py#L4

For trainers, they may only see this when they already told the students to open a jupyter notebook and then they have to close it again, which could be a mess.

My instinct would be to either remove the line profile here either entirely or add the installation of the napari plugin to the tool installation instructions.

What do you think @k-dominik @tibuch ?

**Comment by tischi** [comment]
This may be a different story in later, more advance modules, but to already do some special stuff in the very first module is very likely a mental overload.

**Comment by k-dominik** [comment]
`napari-plot-profile` is also [on conda-forge](https://anaconda.org/conda-forge/napari-plot-profile). I tested the installation and **for me it works**™️ (tested the plugin works, too). I'd be for adding it to the installation instructions.

**Comment by tischi** [comment]
Great! Could you please do this?

For Monday, since I don't want the students now to reinstall their environment I will just skip the line profile part.

But for the next course we will then have it at our finger tips :-)

**Comment by k-dominik** [comment]
will do!

**Comment by tischi** [comment]
Done.
