### ISSUE TITLE
Workflows

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#66]
@manerotoni 
How should we do it with the workflows?
I would just add them as modules.

For example: 
- Workflow 2D nuclei segmentation

**Comment by tischi** [comment]
And then within the workflows one could have the corresponding modules as prerequisites.

**Comment by tischi** [comment]
@manerotoni Could you comment on this? I think adding one or two workflows may be an important step now.

**Comment by manerotoni** [comment]
Yes I will have this week a 2 days session on the course material. We can have a phone call. 
We should add 2D segmentation nuclei (mainly morphological)
2D segmentation of nuclei + nuclear pores (morphological analysis and intensity)
The images for the nuclei should be the same for the 2 examples. I have some examples but can easily acquire some more.
