### ISSUE TITLE
How to save images in python?

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#671]
We are teaching right now saving images using `from OpenIJTIFF import save_ij_tiff`.

This is quite limited, because it currently:

1. Does not work for boolean type images => it should save it as uint8 with 0 and 255
2. It currently does require all metadata in terms of axes => it should simply save an array without metadata and then adding 1 pixel as units

@bugraoezdemir Do you feel like improving this? Or shall we also teach the participants how to use `skimage.io.imsave`?
@k-dominik What do you think?

**Comment by bugraoezdemir** [comment]
@tischi, I can fix those two points before the third day of the course.

**Comment by tischi** [comment]
Thanks a lot @bugraoezdemir !
