### ISSUE TITLE
ImageJ GUI vs Macro Activity

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#68]
@manerotoni 

Quite often (almost always) there is a one-to-one correspondence between a recorded IJ macro and a written description of where you have to click in the GUI. 

In fact, I think an IJ macro could be considered as a concise recipe of what you have to do in the GUI.

Thus, I wonder, whether in the "activities" section, which will be typically guided by the teacher anyway, it could be sufficient to only have the IJ macro version and omit the IJ GUI version.

A disadvantage is that self-learners that want to use this material without any guidance may find it difficult to see and apply this one-to-one correspondence.

So, mainly I guess it would be less work for the lesson developers to not have to add (a tediously formatted) ImageJ GUI version of the activity.

Any thoughts?

cc @haesleinhupef, who also showed some interest of using this repo for, e.g., teaching CLIJ.

**Comment by manerotoni** [comment]
@tischi I would suggest a compromise,
we should try to develop the teaching material and add the IJ macro as default. This guides the teacher and the student. 
For many examples we already have a GUI correspondence.
Personally, I always search for a command through the help and may be this is what we should teach. The GUI and where things are in ImageJ is not very clear. With the macro language you just need to type the string after run.
What do you think?

**Comment by tischi** [comment]
> Personally, I always search for a command through the help and may be this is what we should teach. The GUI and where things are in ImageJ is not very clear. With the macro language you just need to type the string after run.

@manerotoni Yes, I think this is exactly what I meant. So, I agree, _let's always add the macro_ and if someone feels motivated they can also add it as some nicely formatted GUI version. In fact, one could be fancy and write a script that automatically converts the macro into the GUI :-)
