### ISSUE TITLE
Remove template courses

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#708]
Hi @manerotoni,

We currently have template courses here: https://github.com/NEUBIAS/training-resources/tree/master/courses

They start with `YYYY_MM_DD`. I find them hard to keep up to date, usually the most recent actual course is more relevant than the template course. I would propose to remove them. One can take any recent course as a starting point for creating a new one.

What do you think?

**Comment by manerotoni** [comment]
Yes we have so many good examples of real modules. The template is obsolete.

**Comment by tischi** [comment]
> Yes we have so many good examples of real modules. The template is obsolete.

You mean _courses_, right?

**Comment by manerotoni** [comment]
Sorry I got a little bit confused. We have enough examples of course schedules
