### ISSUE TITLE
directly link activities for a specific implementation

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#709]
Hi @manerotoni,

I find it a bit sad that one cannot have URL that would open an activity with a specific implementation.

For example, [this link](https://neubias.github.io/training-resources/pixels/index.html#2d) only opens that activity but leaves the platform unselected. 

I think it would be really cool if there was a possibility to have, e.g., the python activity opened.

What do you think? Do you think it would be worth working on this? I may have some time this week...

**Comment by manerotoni** [comment]
I never missed it, but it can be helpful. Do you think it is hard to implement such a feature?

**Comment by tischi** [comment]
> Do you think it is hard to implement such a feature?

Not sure.... I could give myself one hour to see how far I get....shall I? 

If you think it really is not so important I would work on something else....

I think it could be good, because then in the document for a course one can add not only links to the modules but also to the actual activities, _including_ the correct implementation: https://github.com/NEUBIAS/training-resources/blob/master/courses/2024_07_IDIP-Heidelberg_skimage_napari_beginners.md#image-inspection-basics-day-1

**Comment by manerotoni** [comment]
It would make it more consistent

**Comment by tischi** [comment]
in the end it took my several hours, but I think it was worth it 🥳 

https://neubias.github.io/training-resources/spatial_calibration/index.html?id_activity_platform-1=skimage-napari-activity-1#explore3D

**Comment by manerotoni** [comment]
Cool!
