### ISSUE TITLE
For loops: Simplify?

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#716]
Hi @felixS27,

1. [This line](https://github.com/NEUBIAS/training-resources/blob/a1c1f7d5a8e52699df13111fd4883ea018fcdf6c/_includes/script_for_loop/script_for_loop_python.py#L51) contains relatively advanced string printing. I would say that either we simplify this, or we should make the "string manipulation" module a prerequisite of this module. What do you think (ping @k-dominik)?

2. [This](https://github.com/NEUBIAS/training-resources/blob/a1c1f7d5a8e52699df13111fd4883ea018fcdf6c/_includes/script_for_loop/script_for_loop_python.py#L81) should become a separate activity, otherwise inexperienced teacher may think that they need to show this. OK for you? To do so, the module would need to be refactored to become multi-activities. I can do this...

**Comment by jhennies** [comment]
Also [this one](https://github.com/NEUBIAS/training-resources/blob/a1c1f7d5a8e52699df13111fd4883ea018fcdf6c/_includes/script_for_loop/script_for_loop_python.py#L50) raises quite some questions, do we need it?

**Comment by tischi** [comment]
I would also [remove this](https://github.com/NEUBIAS/training-resources/blob/a1c1f7d5a8e52699df13111fd4883ea018fcdf6c/_includes/script_for_loop/script_for_loop_python.py#L73) and put it into an advanced for-loop activity.

**Comment by tischi** [comment]
> Also [this one](https://github.com/NEUBIAS/training-resources/blob/a1c1f7d5a8e52699df13111fd4883ea018fcdf6c/_includes/script_for_loop/script_for_loop_python.py#L50) raises quite some questions, do we need it?

Not sure, it is a bit advanced, but it does make the point that you could iterate over "what-ever" as along it is a list....

**Comment by jhennies** [comment]
> I would also [remove this](https://github.com/NEUBIAS/training-resources/blob/a1c1f7d5a8e52699df13111fd4883ea018fcdf6c/_includes/script_for_loop/script_for_loop_python.py#L73) and put it into an advanced for-loop activity.

I agree, I think the enumerate version is enough

**Comment by tischi** [comment]
Regarding the advanced string printing, I think actually making the string manipulation a prerequisite of this module could be OK. 

This would allow us to teach something useful like:

```
for index in indices:
    print(f"Analyzing {index}/{len(indices)")
```

**Comment by felixS27** [comment]
> > Also [this one](https://github.com/NEUBIAS/training-resources/blob/a1c1f7d5a8e52699df13111fd4883ea018fcdf6c/_includes/script_for_loop/script_for_loop_python.py#L50) raises quite some questions, do we need it?
> 
> Not sure, it is a bit advanced, but it does make the point that you could iterate over "what-ever" as along it is a list....

I would keep it in, because as @tischi said, it just shows that you can iterate over anything in a list

**Comment by felixS27** [comment]
> > I would also [remove this](https://github.com/NEUBIAS/training-resources/blob/a1c1f7d5a8e52699df13111fd4883ea018fcdf6c/_includes/script_for_loop/script_for_loop_python.py#L73) and put it into an advanced for-loop activity.
> 
> I agree, I think the enumerate version is enough here and the zip functionality is advanced. Also then you could show an actual use case for the zip functionality, since here one would always use the enumerate

Okay, then I will move it to the advanced section and maybe make an example with pairs of coordinates?

**Comment by felixS27** [comment]
> Hi @felixS27,
> 
> 1. [This line](https://github.com/NEUBIAS/training-resources/blob/a1c1f7d5a8e52699df13111fd4883ea018fcdf6c/_includes/script_for_loop/script_for_loop_python.py#L51) contains relatively advanced string printing. I would say that either we simplify this, or we should make the "string manipulation" module a prerequisite of this module. What do you think (ping @k-dominik)?
> 2. [This](https://github.com/NEUBIAS/training-resources/blob/a1c1f7d5a8e52699df13111fd4883ea018fcdf6c/_includes/script_for_loop/script_for_loop_python.py#L81) should become a separate activity, otherwise inexperienced teacher may think that they need to show this. OK for you? To do so, the module would need to be refactored to become multi-activities. I can do this...

I will change it and make two scripts out of it.

**Comment by felixS27** [comment]
I split the script into "beginner" and "advanced". So from my side, we can close this issue, if everyone agrees.

**Comment by tischi** [comment]
Yes, thanks a lot!!
