### ISSUE TITLE
Multiple activities

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#82]
@tobyhodges @manerotoni 

I think quite often one would like to have more than one activity. Right now I solved it like this:

![image](https://user-images.githubusercontent.com/2157566/105182698-a3852500-5b2d-11eb-8eaf-cab2ec19dece.png)

See here for the code: https://raw.githubusercontent.com/NEUBIAS/training-resources/master/_modules/connected_components.md

Any ideas how to make this more beautiful?
Maybe allow for multiple sections in activities?

**Comment by manerotoni** [comment]
You could also solve it by having one activity files with several subsections? This is how I prefer it as it makes less files. I often do not create a preamble, but I think it is useful to see what it is about.
