### ISSUE TITLE
Create a course specific order

### ISSUE THREAD

**Issue by manerotoni** [NEUBIAS/training-resources#85]
Hello @tischi and @tobyhodges,

I understand that we can change the config file and impose an order in the teaching material. This is a very good strategy for a specific course. 

We could fork the repo and create a different config file. However, where is then the rendered page of the master branch found? 
Alternatively we can work on the main branch and create for the time of the course a specific config files. This will for sure work but it is not very clean. 

Thanks

Antonio

**Comment by tobyhodges** [comment]
For NEUBIAS courses, I would recommend using this repository as a template for creating the pages: we can mark this repository as a template and then you can choose it from a dropdown when you create the new repository. After that, you can adjust the `config.yml` and get the site setup for that specific course.

For any repository with GitHub Pages enabled, the pages are served at `https://<username_or_orgname>.github.io/<projectname>/`, so your fork of this repo would have pages at `https://manerotoni.github.io/training-resources/`

**Comment by manerotoni** [comment]
I still don't understand exactly how you would do it. We work all the time on the Neubias repo. Would we create a new branch for the specific order? Or you have a config file with different setups enabled.

Is this a different site or the user choose from the rendered site a different setup.

Thanks for your help

**Comment by manerotoni** [comment]
BTW the site specific creation of the github pages worked very nicely. 
I just activated the github pages and it worked!!!

**Comment by tobyhodges** [comment]
Each different setup will need to be in a different repo and rendering a different site.

**Comment by manerotoni** [comment]
Can we do it from the NEUBIAS site?
