### ISSUE TITLE
Examples how to use the material

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#86]
@manerotoni When the course is over I think it would be great if we could add some short version of our whole course schedule (how we combined the modules etc) into the README (probably as a link to somewhere).

**Comment by manerotoni** [comment]
I think this should be done within  the ordering of the course that we specify in the config module. See also
https://github.com/NEUBIAS/training-resources/issues/85

**Comment by manerotoni** [comment]
Creating a branch at the end of the course with the corresponding config file and additional material.
