### ISSUE TITLE
Open images from URL

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#89]
@manerotoni 

This is awesome (runs in IJ Macro):

```
open("https://github.com/NEUBIAS/training-resources/raw/master/image_data/xy_8bit_binary__nuclei.tif");
```

I am putting this now in all the macros of "my" modules.

**Comment by manerotoni** [comment]
Gret idea.

**Comment by manerotoni** [comment]
You can even drag and drop into Fiji !! at least from OSX
