### ISSUE TITLE
Rendering of java code bug

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#95]
@tobyhodges 

The java code rendering assigns funny colors to words within block comments.
```Java
/**
* This is a comment
* /
```
Any chance we could teach it not to do this?

![image](https://user-images.githubusercontent.com/2157566/105636994-55448e80-5e6b-11eb-98b2-44db310b0c57.png)

**Comment by manerotoni** [comment]
On firefox it looks good now
